### ISSUE TITLE
`npm init video` throws an error

### ISSUE THREAD

**Issue by Seruf-Che** [remotion-dev/remotion#1081]
# Bug Report 🐛

There is an issue when execute `npm init video`

Error:
```✔ What would you like to name your video? … my-video
✔ Choose a template: › Hello World               The default starter template (recommended)
Copied Hello World to my-video. Installing dependencies...
> npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@types/eslint@https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-06-30T21_11_50_752Z-debug-0.log
Error: Command failed with exit code 1: npm install --no-fund
    at makeError (/home/user/.npm/_npx/40176cad2f2d1409/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/user/.npm/_npx/40176cad2f2d1409/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async init (/home/user/.npm/_npx/40176cad2f2d1409/node_modules/create-video/dist/init.js:101:9) {
  shortMessage: 'Command failed with exit code 1: npm install --no-fund',
  command: 'npm install --no-fund',
  escapedCommand: 'npm install --no-fund',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
npm ERR! code 1
npm ERR! path /home/user/Projects/remotion
npm ERR! command failed
npm ERR! command sh -c /tmp/npx-1656623506323.sh
```

The same with `yarn create video`

#### versions
OS: Ubuntu 20.04
Node: 16.15.1
npm: 8.13.1
yarn: 1.22.19
ffmpeg version 4.2.7-0ubuntu0.1

**Comment by rfoel** [comment]
Try using `yarn`, it worked for me.
```
yarn create video
```

**Comment by JonnyBurger** [comment]
It seems to work now, no more 404 when visiting the URL, I think the npm registry still had a caching problem.

See also: https://stackoverflow.com/questions/72821229/how-should-i-resolve-this-error-that-occurs-when-using-ng-new
