### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by AbhishekPatnaik** [remotion-dev/remotion#1487]
# Bug Report 🐛

`Error: Cannot find module 'fs/promises'
Require stack:
- /Users/abhishekpatnaik/my-video/node_modules/@remotion/renderer/dist/stitch-frames-to-video.js
- /Users/abhishekpatnaik/my-video/node_modules/@remotion/renderer/dist/render-media.js
- /Users/abhishekpatnaik/my-video/node_modules/@remotion/renderer/dist/index.js
- /Users/abhishekpatnaik/my-video/node_modules/@remotion/cli/dist/index.js
- /Users/abhishekpatnaik/my-video/node_modules/@remotion/cli/remotion-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/abhishekpatnaik/my-video/node_modules/@remotion/renderer/dist/stitch-frames-to-video.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/abhishekpatnaik/my-video/node_modules/@remotion/renderer/dist/stitch-frames-to-video.js',
    '/Users/abhishekpatnaik/my-video/node_modules/@remotion/renderer/dist/render-media.js',
    '/Users/abhishekpatnaik/my-video/node_modules/@remotion/renderer/dist/index.js',
    '/Users/abhishekpatnaik/my-video/node_modules/@remotion/cli/dist/index.js',
    '/Users/abhishekpatnaik/my-video/node_modules/@remotion/cli/remotion-cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-video@1.0.0 start: `remotion preview``

**Hey guys, i get this Error in the screenshot when i try to run "npm start". any guess why this is happening?**

**Comment by JonnyBurger** [comment]
Hey @AbhishekPatnaik! 

This error occurs because you are using an old Node version. We only support Node 14 and above.
We could handle this better and show an error message, and I just fixed that in #1489!

**Comment by AbhishekPatnaik** [comment]
Thanks  @JonnyBurger the Issue is solved !!
