### ISSUE TITLE
`MaxListenersExceededWarning` issue with `@remotion/bundler` and `@remotion/renderer`

### ISSUE THREAD

**Issue by MatteoGauthier** [remotion-dev/remotion#1543]
Got an issue using `@remotion/bundler` and `@remotion/renderer`

here is the error logs 

```ts
(node:80049) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:80049) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:80049) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:80049) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit
/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/ExecutionContext.js:119
        throw new Error('Evaluation failed: ' + (0, util_1.getExceptionMessage)(exceptionDetails));
              ^


Error: Evaluation failed: ReferenceError: __name is not defined
    at pptr://__puppeteer_evaluation_script__:1:387
    at new Promise (<anonymous>)
    at waitForPredicatePageFunction (pptr://__puppeteer_evaluation_script__:1:203)
    at ExecutionContext._ExecutionContext_evaluate (/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/ExecutionContext.js:119:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WaitTask.rerun (/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/DOMWorld.js:186:23)

Node.js v18.12.1
 ELIFECYCLE  Command failed with exit code 1.
```

and here is my `render.ts` file 

```typescript
import { bundle } from '@remotion/bundler';
import { getCompositions, renderMedia } from '@remotion/renderer';
import path from 'path';
import videosData from '../../data/videos.json';
import { RedditTiktokTestProps } from '../compositions/RedditTiktokTest';

const renderOne = async (
	redditVideo: RedditTiktokTestProps,
	bundleLocation: string,
	compositionId: string,
	entry: string
) => {
	// Parametrize the video by passing arbitrary props to your component.

	// Extract all the compositions you have defined in your project
	// from the webpack bundle.
	const comps = await getCompositions(bundleLocation, {
		// You can pass custom input props that you can retrieve using getInputProps()
		// in the composition list. Use this if you want to dynamically set the duration or
		// dimensions of the video.
		inputProps: redditVideo,
	});

	// Select the composition you want to render.
	const composition = comps.find((c) => c.id === compositionId);

	// Ensure the composition exists
	if (!composition) {
		throw new Error(`No composition with the ID ${compositionId} found.
  Review "${entry}" for the correct ID.`);
	}

	const currentDate = new Date().toISOString().split('T')[0];
	const outputLocation = `out/${currentDate}_${redditVideo.id}.mp4`;
	console.log('⏳ Attempting to render:', outputLocation);
	const startTimer = performance.now();

	await renderMedia({
		composition,
		serveUrl: bundleLocation,
		codec: 'h264',
		outputLocation,
		inputProps: redditVideo,
		imageFormat: 'jpeg',
		quality: 75,
		overwrite: true,
		concurrency: 6,
	});
	const stopTimer = performance.now();

	const inSeconds = (stopTimer - startTimer) / 1000;
	const rounded = Number(inSeconds).toFixed(3);
	console.log(`✅ Render done in ${rounded}s!`);
};

async function start() {
	const startTimer = performance.now();

	// The composition you want to render
	const compositionId = 'RedditTiktokTest';

	// You only have to do this once, you can reuse the bundle.
	const entry = 'src/index.ts';
	console.log('🔧 Creating a Webpack bundle of the video');

	const bundleLocation = await bundle(path.resolve(entry), () => undefined, {
		// If you have a Webpack override, make sure to add it here
		webpackOverride: (config) => config,
	});

	videosData.forEach(async (element: RedditTiktokTestProps) => {
		await renderOne(element, bundleLocation, compositionId, entry);
	});
	const stopTimer = performance.now();

	const inSeconds = (stopTimer - startTimer) / 1000;
	const rounded = Number(inSeconds).toFixed(3);
	console.log(`🎉 All videos have been rendered in ${rounded}s!`);
}

start();

```

Does someone can help me ?

**Comment by JonnyBurger** [comment]
Hi Mattèo!

It looks like you are rendering all the videos at once, which might put the system under stress and can lead to crashes. From your code it could be that you did this unintentionally.

Try changing:

```ts
videosData.forEach(async (element: RedditTiktokTestProps) => {
		await renderOne(element, bundleLocation, compositionId, entry);
});
```

to:

```ts
for (const element of videosData) {
		await renderOne(element, bundleLocation, compositionId, entry);
}
```

This will render the videos in sequence rather than in parallel.

**Comment by MatteoGauthier** [comment]
Hi @JonnyBurger thanks for your solution, I changed the loop to use a for, and I still have a problem but with `puppeteer` now...

```
/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/ExecutionContext.js:119
        throw new Error('Evaluation failed: ' + (0, util_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: ReferenceError: __name is not defined
    at pptr://__puppeteer_evaluation_script__:1:387
    at new Promise (<anonymous>)
    at waitForPredicatePageFunction (pptr://__puppeteer_evaluation_script__:1:203)
    at ExecutionContext._ExecutionContext_evaluate (/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/ExecutionContext.js:119:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at WaitTask.rerun (/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/DOMWorld.js:186:23)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by JonnyBurger** [comment]
@MatteoGauthier Can you paste in here what your `videosData` is like? Maybe it is not serilalizable. Also, do you reference `__name` somewhere in your Remotion code?

**Comment by JonnyBurger** [comment]
I don't know why you got this error specifically! I got a different one when running the script: `No "src" passed`.

From that I was able to fix it, sent you a PR!

**Comment by MatteoGauthier** [comment]
@JonnyBurger Thanks a lot for your PR, I've merged it but I still have the same issue.
```
➜  reddit-to-tiktok-remotion git:(main) pnpm render         

> reddit-to-tiktok-remotion@1.0.0 render /Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion
> tsx ./src/script/reddit-videos.ts && tsx ./src/script/render.ts

🔧 Creating a Webpack bundle of the video
/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/ExecutionContext.js:119
        throw new Error('Evaluation failed: ' + (0, util_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: ReferenceError: __name is not defined
    at pptr://__puppeteer_evaluation_script__:1:387
    at new Promise (<anonymous>)
    at waitForPredicatePageFunction (pptr://__puppeteer_evaluation_script__:1:203)
    at ExecutionContext._ExecutionContext_evaluate (/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/ExecutionContext.js:119:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at WaitTask.rerun (/Users/matteogauthier/dev/draft/reddit-to-tiktok-remotion/node_modules/.pnpm/@remotion+renderer@3.3.7_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/renderer/dist/browser/DOMWorld.js:186:23)
```

**Comment by JonnyBurger** [comment]
Thanks, good luck with your bot! 🙌
