### ISSUE TITLE
`remotion render` fails when directory `node_modules` does not exist

### ISSUE THREAD

**Issue by mxro** [remotion-dev/remotion#1629]
When initialising a new project with remotion using a package manager that doesn't create a `node_modules` (such as [Yarn 3](https://yarnpkg.dev/releases/3-0/), running the `build` script results in an error.

Ideally, the `remotion render` command should create the `node_modules` folder when it doesn't exist.

# Bug Report 🐛

Running the `build` script when the folder `node_modules` does not exist results in the following error:

```
Max@DESKTOP-B5B5HEH MINGW64 ~/repos/docblitz-course/packages/remotion (master)
$ yarn build

An error occurred:
Error: ENOENT: no such file or directory, mkdir 'C:\Users\Max\repos\docblitz-course\packages\remotion\node_modules\.ffmpeg'
    at Object.mkdirSync (node:fs:1349:3)
    at NodeFS.mkdirSync (C:\Users\Max\repos\docblitz-course\.pnp.cjs:8483:24)
    at makeCallSync.subPath.subPath (C:\Users\Max\repos\docblitz-course\.pnp.cjs:10728:26)
    at ZipOpenFS.makeCallSync (C:\Users\Max\repos\docblitz-course\.pnp.cjs:10913:14)
    at ZipOpenFS.mkdirSync (C:\Users\Max\repos\docblitz-course\.pnp.cjs:10727:17)
    at VirtualFS.mkdirSync (C:\Users\Max\repos\docblitz-course\.pnp.cjs:10009:24)
    at PosixFS.mkdirSync (C:\Users\Max\repos\docblitz-course\.pnp.cjs:10009:24)
    at URLFS.mkdirSync (C:\Users\Max\repos\docblitz-course\.pnp.cjs:10009:24)
    at ffmpegInNodeModules (C:\Users\Max\repos\docblitz-course\.yarn\__virtual__\@remotion-renderer-virtual-38a9ac8efd\0\cache\@remotion-renderer-npm-3.3.19-23c5bb4470-1222c69955.zip\node_modules\@remotion\renderer\dist\ffmpeg-flags.js:35:22)
    at Object.validateFfmpeg (C:\Users\Max\repos\docblitz-course\.yarn\__virtual__\@remotion-renderer-virtual-38a9ac8efd\0\cache\@remotion-renderer-npm-3.3.19-23c5bb4470-1222c69955.zip\node_modules\@remotion\renderer\dist\validate-ffmpeg.js:67:48)
```

Possibly there could be a better place for the `.ffmpeg` folder that does not assume that a `node_modules` folder exists?

# Workaround

Everything seems to work fine after creating the `node_modules` folder manually using `mkdir node_modules`.

**Comment by JonnyBurger** [comment]
Thanks for the report! 
Indeed we should create the `node_modules` folder then. Hoping to fix soon!

**Comment by JonnyBurger** [comment]
Gonna make a node_modules folder still due to lack of a better place to put it.
It's already in the .gitignore and we want to scope the binary to the project, not install it globally.
