### ISSUE TITLE
ENOENT on recomended template due to /public not existing   

### ISSUE THREAD

**Issue by jeankhoury0** [remotion-dev/remotion#1643]
On first installation,  using the step bellow getting an Error: ENOENT: no such file or directory, watch '/Volumes/workspace/draft/replicatebug/my-video/public. Most likely this is due to the /public directory not existing
**Note**: I was able to make it work by manually adding the public folder.  

# Step to replicate
- Run ```npm init video```
- Name video with default (my-video)
- Use default template (Hello World, The default starter template (recommended)
- cd into directory
- Run ``` npm i ``` to install dependecies
- Run ``` npm start ```

# Software
- Apple M1 Pro, OSX 13.1 (22C65), node v19.1.0 

# Terminal output: 
``` zsh
An error occurred:
Error: ENOENT: no such file or directory, watch '/Volumes/workspace/draft/replicatebug/my-video/public'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at watch (node:fs:2310:36)
    at watchPublicFolder (/Volumes/workspace/draft/replicatebug/my-video/node_modules/@remotion/cli/dist/preview-server/public-folder.js:31:20)
    at initPublicFolderWatch (/Volumes/workspace/draft/replicatebug/my-video/node_modules/@remotion/cli/dist/preview-server/public-folder.js:13:35)
    at previewCommand (/Volumes/workspace/draft/replicatebug/my-video/node_modules/@remotion/cli/dist/preview.js:91:47)
    at async cli (/Volumes/workspace/draft/replicatebug/my-video/node_modules/@remotion/cli/dist/index.js:68:13)
```

**Comment by JonnyBurger** [comment]
Oh right, this is a regression from yesterdays release. Gonna put in a fix immediately!

**Comment by ursnj** [comment]
Same issue for me too ...

**Comment by JonnyBurger** [comment]
New release will be out shortly, either upgrade, or easy workaround is to create a `public/` folder.
