### ISSUE TITLE
Multiple versions check bug

### ISSUE THREAD

**Issue by jmaguirrei** [remotion-dev/remotion#1869]
Hello, I am getting an error

```
multiple-versions-warning.js:18 Uncaught (in promise) TypeError: 🚨 Multiple versions of Remotion detected: 3.3.56 and 3.3.56. This will cause things to break in an unexpected way.
Check that all your Remotion packages are on the same version. If your dependencies depend on Remotion, make them peer dependencies. You can also run `npx remotion versions` from your terminal to see which versions are mismatching.
    at checkMultipleRemotionVersions (multiple-versions-warning.js:18:15)
    at node_modules/remotion/dist/cjs/index.js (index.js:23:36)
    at __require2 (chunk-TFWDKVI3.js?v=871ffd37:18:50)
    at node_modules/@remotion/google-fonts/dist/base.js (base.js:4:20)
    at __require2 (chunk-TFWDKVI3.js?v=871ffd37:18:50)
    at node_modules/@remotion/google-fonts/dist/Montserrat.js (Montserrat.js:4:16)
    at __require2 (chunk-TFWDKVI3.js?v=871ffd37:18:50)
    at Montserrat.js:155:20
```

As the error shows, it's clear than version 3.3.56 is the only version.

Looking at this file: [remotion](https://github.com/remotion-dev/remotion)/[packages](https://github.com/remotion-dev/remotion/tree/main/packages)/[core](https://github.com/remotion-dev/remotion/tree/main/packages/core)/[src](https://github.com/remotion-dev/remotion/tree/main/packages/core/src)/multiple-versions-warning.ts 

It looks it does not actually compare values, only having more than one.

This causes the whole `<Player/>` to crash.

**Comment by JonnyBurger** [comment]
Sorry for missing this on Discord!
I think this is ESM behavior that a module can be imported multiple times.
Fix coming in shortly.
