### ISSUE TITLE
`Access Denied` error when running `npx remotion lambda quotas increase`

### ISSUE THREAD

**Issue by Just-Moh-it** [remotion-dev/remotion#1941]
# Bug Report 🐛

I followed the lambda setup docs and then requested a quota increase with the access key and secret I got. But running the quota increase command results in access denied error.

```bash
❯ npx remotion lambda quotas increase

Sending request to AWS to increase concurrency limit from 10 to 5000.
Send? (Y/n) 
AWS returned an "AccessDenied" error message meaning a permission is missing. Read the permissions troubleshooting page: https://remotion.dev/docs/lambda/troubleshooting/permissions. The original error message is:
DependencyAccessDeniedException: Service-linked role creation access denied.
    at deserializeAws_json1_1DependencyAccessDeniedExceptionResponse (/Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@aws-sdk+client-service-quotas@3.272.0/node_modules/@aws-sdk/client-service-quotas/dist-cjs/protocols/Aws_json1_1.js:1198:23)
    at deserializeAws_json1_1RequestServiceQuotaIncreaseCommandError (/Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@aws-sdk+client-service-quotas@3.272.0/node_modules/@aws-sdk/client-service-quotas/dist-cjs/protocols/Aws_json1_1.js:1047:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@aws-sdk+middleware-serde@3.272.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@aws-sdk+middleware-signing@3.272.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@aws-sdk+middleware-retry@3.272.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@aws-sdk+middleware-logger@3.272.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async quotasIncreaseCommand (/Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@remotion+lambda@3.3.77_zsgd5zadldtgnvqda7o3d6gbwy/node_modules/@remotion/lambda/dist/cli/commands/quotas/increase.js:50:5)
    at async Object.executeCommand (/Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@remotion+lambda@3.3.77_zsgd5zadldtgnvqda7o3d6gbwy/node_modules/@remotion/lambda/dist/cli/index.js:103:9)
    at async lambdaCommand (/Users/mohit/dev/repurpose/repurpose-editor/node_modules/.pnpm/@remotion+cli@3.3.77_biqbaboplfbrettd7655fr4n2y/node_modules/@remotion/cli/dist/lambda-command.js:13:9)
```

**Comment by Just-Moh-it** [comment]
cc @JonnyBurger

**Comment by Just-Moh-it** [comment]
@JonnyBurger thanks for the quick fix! ✨

Though in my case, I have two different aws accounts from two different clients, and they gave me the login to their AWS root account. And when I followed the instructions based on the lambda setup and created an aws user (I assume it would be a root user since it was created when the root user was logged in... though I may very well be incorrect), I get the error in the first comment.

Not sure if by the root user, you mean the user that has to be logged in to the aws console to follow through the lambda setup docs or the user that is created by following the lambda setup docs and for which we get the access key and secret for.

**Comment by Just-Moh-it** [comment]
Oh, now that I saw the PR, it's confirmed my assumption from the above comment was wrong.

While using remotion's cli, I usually assume that the subaccount created by following the remotion lambda setup docs would be able to run ever remotion cli command, and I believe most remotion users do this too. If that's correct, maybe add a warning to the quotas increase command that you need to be the root user (which was used to follow through the lambda setup docs) to use this command. Thanks!

**Comment by JonnyBurger** [comment]
Subaccounts are still normal accounts with username/password, you go to AWS settings and  then Organizations to see them, that's what I meant. Maybe you can go there and see if you are asubaccount?

Generally: you are a sub acocunt if you don't pay your own bills
