### ISSUE TITLE
[BUG] remotion build with video

### ISSUE THREAD

**Issue by LeGitHubDeTai** [remotion-dev/remotion#2438]
# Bug Report 🐛

Here's the step-by-step process I followed to create the project:

1. Ran the command `npm init video` to initialize the video project.
2. Selected the "Hello world" option for JavaScript.
3. Added a file named `Comp.jsx` inside the `HelloWorld` folder. In this file, I included the following code snippet, which I found in the official documentation:

```jsx
import { Video } from "remotion";

export const MyComp: React.FC = () => {
  return (
    <Video src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" />
  );
};
```

After that, I made modifications to the `HelloWorld/index.jsx` file as follows:

```jsx
import { spring } from 'remotion';
import {
	AbsoluteFill,
	interpolate,
	Sequence,
	useCurrentFrame,
	useVideoConfig,
} from 'remotion';
import { Logo } from './Logo';
import { Subtitle } from './Subtitle';
import { Title } from './Title';
import { MyComp } from './Comp';

export const HelloWorld = ({ titleText, titleColor }) => {
	const frame = useCurrentFrame();
	const { durationInFrames, fps } = useVideoConfig();

	// Animating the logo from 0 to 1 after 25 frames
	const logoTranslationProgress = spring({
		frame: frame - 25,
		fps,
		config: {
			damping: 100,
		},
	});

	// Moving the logo up by 150 pixels once the transition starts
	const logoTranslation = interpolate(
		logoTranslationProgress,
		[0, 1],
		[0, -150]
	);

	// Fading out the animation at the end
	const opacity = interpolate(
		frame,
		[durationInFrames - 25, durationInFrames - 15],
		[1, 0],
		{
			extrapolateLeft: 'clamp',
			extrapolateRight: 'clamp',
		}
	);

	// The <AbsoluteFill> component represents an absolutely positioned <div>!
	return (
		<AbsoluteFill style={{ backgroundColor: 'white' }}>
			<AbsoluteFill style={{ opacity }}>
				<AbsoluteFill style={{ transform: `translateY(${logoTranslation}px)` }}>
					<Logo />
				</AbsoluteFill>
				{/* Sequences can shift the time for its children! */}
				<Sequence from={35}>
					<Title titleText={titleText} titleColor={titleColor} />
				</Sequence>
				{/* The subtitle will only enter on the 75th frame. */}
				<Sequence from={75}>
					<Subtitle />
				</Sequence>
			</AbsoluteFill>
			<MyComp></MyComp>
		</AbsoluteFill>
	);
};
```

And here's what I'm getting, and I don't understand where it's coming from. I've used Remotion in the past, and everything was working fine. I believe a recent update broke everything.

```bash
> remotion render HelloWorld temp/out.mp4

(1/3) ╭───────────────────╮ Bundled code 596ms
Entry point = src\index.js (common paths), Composition = HelloWorld (Passed as argument), Codec = h264 (derived from out name), Output = temp/out.mp4
(2/3) ╭───────────────────╮ Rendered frames (8x) 32617ms
    + ╭───────────────────╮ Downloading https://commondatastorage.googleapis.com/gtv-videos-bucke...
(3/3) ╭──────────           Muxing video 75/150
An error occurred:
Error: Command failed with exit code 1: ffmpeg -i Local\Temp\remotion-v3-3-101-assetset18x6m6qf\remotion-audio-mixing\0.wav -filter_complex_script Local\Temp\remotion-v3-3-101-assetset18x6m6qf\remotion-complex-filter\complex-filter-08983999909845033.txt -c:a pcm_s16le -map [outputaudio] -y Local\Temp\remotion-v3-3-101-assetset18x6m6qf\remotion-audio-preprocessing\audio.wav
ffmpeg version git-2020-01-15-0dc0837 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200111
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 65.103 / 58. 65.103
  libavformat    58. 35.102 / 58. 35.102
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 71.100 /  7. 71.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from 'Local\Temp\remotion-v3-3-101-assetset18x6m6qf\remotion-audio-mixing\0.wav':
  Metadata:
    encoder         : Lavf58.35.102
  Duration: 00:00:05.00, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s
[Parsed_amix_1 @ 000002108fe61a80] Option 'normalize' not found
[AVFilterGraph @ 000002108fa957c0] Error initializing filter 'amix' with args 'inputs=1:dropout_transition=0:normalize=0'
Error initializing complex filters.
Option not found
    at makeError (projectName\node_modules\execa\lib\error.js:60:11)
    at handlePromise (projectName\node_modules\execa\index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async mergeAudioTrackUnlimited (projectName\node_modules\@remotion\renderer\dist\merge-audio-track.js:82:5)
```

**Comment by JonnyBurger** [comment]
Hey, thanks for reporting!

This seems to be because you have an FFmpeg version which is unversioned and we don't recognize that it is an old version which doesn't support this filter yet.

You can either upgrade FFmpeg to fix it or use the V4 Alpha: https://v4.remotion.dev/docs/4-0-alpha
We fixed it in this version by shipping our own version of FFmpeg. Should be out in ~10 days!

For V3, we unfortunately don't have a good fix because if we removed this filter, this version that you have installed would produce unexpected audio mixing.

**Comment by LeGitHubDeTai** [comment]
insane, it works i didn't think i had to update ffmpeg. but the bug is not clear x)
