### ISSUE TITLE
renderMediaOnLambda() - Can't access inputProps passed. Returns undefined for <Video /> src. - Lambda Error. 

### ISSUE THREAD

**Issue by jackkingham-au** [remotion-dev/remotion#2455]
I have a Remotion Composition, ready to render on Remotion Lambda. 

Running this same Composition with `npx remotion preview` or `npx remotion render` on my local machine, renders the video exactly as desired.

When I call renderMediaOnLambda(), I always get progress to 22.5% before it stops with an error - The ```<Video>``` tag requires a string for ```src```, but got ```undefined``` instead.

I believe there is an error with the inputProps, being passed into the render function. For some reason, the inputProps seem to be inaccessible.

To give context on the issue;

_Root.tsx_
```
import { Composition, getInputProps, staticFile } from "remotion";
import "../styles/globals.css";
import ExportTimeline from "./ExportTimeline/Composition";
import { ExportTimelineProps } from "../types/remotion";

const sampleVideo = staticFile('/video/portrait-sample-video.mp4');
const inputProps: ExportTimelineProps = getInputProps();

const defaultProps = {
    // @ts-ignore
    segments:  [
        {
            "src":"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/video/c59d4e9e-b0df-4bf0-a83e-8682e4da6280.mp4",
            "templateSrc":"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/template/081953bf-b982-4479-b1a3-59e372d714b2.txt","id":"c59d4e9e-b0df-4bf0-a83e-8682e4da6280"
        },
        {
            "src":"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/video/95e81c95-1d52-478b-b586-4451a1b34fcd.mp4",
            "templateSrc":"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/template/c02c7ea9-553b-4aa3-a127-ad0f2c5341d2.txt","id":"95e81c95-1d52-478b-b586-4451a1b34fcd"
        }
    ],
    metrics: {
        fps: 30,
        compositionHeight: 1920,
        compositionWidth: 1080,
        aspectRatio: '9/16',
        maxLimit: 5,
        totalDurationInFrames: 300,
        segmentDurationInFrames: 150,
        totalDurationInSeconds: 10,
    }
}

export const Root = () => {

    if(Object.keys(inputProps).length > 0) return (
        <Composition
            id="Export"
            durationInFrames={inputProps.metrics.totalDurationInFrames}
            component={ExportTimeline}
            fps={inputProps.metrics.fps}
            width={inputProps.metrics.compositionWidth}
            height={inputProps.metrics.compositionHeight}
        />
    )

    return (
        <Composition
            id="Export"
            durationInFrames={defaultProps.metrics.totalDurationInFrames}
            component={ExportTimeline}
            fps={defaultProps.metrics.fps}
            width={defaultProps.metrics.compositionWidth}
            height={defaultProps.metrics.compositionHeight}
            defaultProps={defaultProps}
        />
    );
};
```

_Composition.tsx (Export Timeline)_
```
import { ExportTimelineProps } from "@/types/remotion/";
import DefaultComposition from "./DefaultComposition";
import DynamicComposition from "./DynamicComposition";

const ExportTimeline = (props : ExportTimelineProps) => {   

    return <DynamicComposition { ...props } />
}

export default ExportTimeline;
```

_DynamicComposition.tsx_
```
import { ExportTimelineProps } from "@/types/remotion";
import { Sequence, Video, delayRender, continueRender } from "remotion";
import Transition from "../../components/transitions/Fade";
import StaticTemplate from "./StaticTemplate";
import { useState, useCallback, useEffect } from "react";
import { ExportedSegment } from "@/types/config/appSettings";

const getRawTemplates = (segments: ExportedSegment[]) => {
    return Promise.all(segments.map((segment) => {
        return fetch(segment.templateSrc!).then(res => res.text()).then(res => {
            return {
                for: segment.id,
                template: res
            }
        })
    }))
}

const DynamicComposition = (props: ExportTimelineProps) => {
    const segments = props.segments!;
    const metrics = props.metrics;

    const [rawTemplates, setRawTemplates] = useState<null | { template: string | null, for: string }[]>(null);
    const [handle] = useState(() => delayRender());
    
    const getDynamicProps = useCallback(async () => {
        setRawTemplates(await getRawTemplates(segments));
        continueRender(handle);
    }, [handle]);
    
    useEffect(() => { getDynamicProps() }, []);

    return (
        <>
            {
                segments!.map(({src, id}, index) => {
                    const rawTemplate = rawTemplates?.filter(template => template.for === id)[0];

                    return (
                        <Sequence
                            durationInFrames={metrics.segmentDurationInFrames}
                            from={index === 0 ? 0 : index * metrics.segmentDurationInFrames}
                            key={index}
                        >
                            <Video src={src} />
                            <Transition metrics={props.metrics} />
                            {
                                (rawTemplate)
                                ? <StaticTemplate template={rawTemplate.template!} />
                                : ''
                            }
                            
                        </Sequence>
                    )
                })
            }    
        </>
    )
    
}

export default DynamicComposition;
```

_Fade.tsx (Transition)_
```
import { RemotionMetrics } from "@/types/remotion";
import { useCurrentFrame, interpolate, AbsoluteFill } from "remotion";

const Transition = ({metrics} : { metrics: RemotionMetrics }) => {
    const { fps, segmentDurationInFrames } = metrics;

    const currentFrame = useCurrentFrame();
    const transitionFrameDuration = fps / 2; // 15

    const opacity = interpolate(
        currentFrame,
        [0, transitionFrameDuration, segmentDurationInFrames - transitionFrameDuration, segmentDurationInFrames],
        [1, 0, 0, 1] 
    );

    return (
        <AbsoluteFill 
            className="bg-black min-h-full min-w-full z-50"
            style={{opacity}}
        />
    )
}

export default Transition;
```

_StaticTemplate.tsx_ simply renders an `<AbsoluteFill />` with an image to overlay the video.

**Copy of Error Returned from `getRenderProgress()`**
```
progress: 0.225,
output: null,
details: {
framesRendered: 0,
chunks: 0,
done: false,
encodingStatus: null,
costs: {
accruedSoFar: 0.33128,
displayCost: "$0.331",
currency: "USD",
disclaimer: "Estimated cost only. Does not include charges for other AWS services."
},
renderId: "0iwkxi06rb",
renderMetadata: {
startedDate: 1687911400618,
videoConfig: {
durationInFrames: 300,
fps: 30,
height: 1920,
id: "Export",
width: 1080
},
totalChunks: 15,
estimatedTotalLambdaInvokations: 16,
estimatedRenderLambdaInvokations: 15,
compositionId: "Export",
siteId: "54c0e0b57731978a8209f14877512547",
codec: "h264",
type: "video",
imageFormat: "jpeg",
inputProps: {
type: "payload",
payload: "{"segments":["{\"src\":\"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/video/45c9c167-8a72-42c4-ae8b-cb1bd4642124.mp4\",\"templateSrc\":\"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/template/c238620b-2340-45fe-8bc4-6076b1bbc538.txt\",\"id\":\"45c9c167-8a72-42c4-ae8b-cb1bd4642124\"}","{\"src\":\"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/video/e4e45ae3-24c4-4ec8-9939-bfa05d4ecf5a.mp4\",\"templateSrc\":\"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/template/6c723a0b-f38b-4857-b093-1d3c7eaf5dee.txt\",\"id\":\"e4e45ae3-24c4-4ec8-9939-bfa05d4ecf5a\"}"],"metrics":{"fps":30,"compositionHeight":1920,"compositionWidth":1080,"aspectRatio":"9/16","maxLimit":5,"totalDurationInFrames":300,"segmentDurationInFrames":150,"totalDurationInSeconds":10}}"
},
lambdaVersion: "3.3.102",
framesPerLambda: 20,
memorySizeInMb: 2048,
region: "us-east-1",
renderId: "0iwkxi06rb",
privacy: "public",
everyNthFrame: 1,
frameRange: [
0,
299
],
audioCodec: null
},
bucket: "remotionlambda-useast1-xy3lng8g6a",
outputFile: null,
timeToFinish: null,
errors: [
{
attempt: 1,
chunk: null,
explanation: "The main function timed out after 119999ms.
Consider increasing the timeout of your function.
The following chunks are missing (showing 5 out of 15): Chunk 0 (Frames 0 - 19), Chunk 1 (Frames 20 - 39), Chunk 2 (Frames 40 - 59), Chunk 3 (Frames 60 - 79), Chunk 4 (Frames 80 - 99).
You can use the "--timeout" parameter when deploying a function via CLI, or the "timeoutInSeconds" parameter when using the deployFunction() API.
https://remotion.dev/docs/lambda/cli/functions#deploy",
frame: null,
isFatal: true,
s3Location: "",
stack: "Error
    at makeTimeoutError (/var/task/index.js:179123:12)
    at getProgress (/var/task/index.js:179305:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /var/task/index.js:180019:24
    at async Object.apply (/var/task/index.js:174007:7)",
tmpDir: null,
totalAttempts: 1,
type: "stitcher",
willRetry: false,
message: "The main function timed out after 119999ms.
Consider increasing the timeout of your function.
The following chunks are missing (showing 5 out of 15): Chunk 0 (Frames 0 - 19), Chunk 1 (Frames 20 - 39), Chunk 2 (Frames 40 - 59), Chunk 3 (Frames 60 - 79), Chunk 4 (Frames 80 - 99).
You can use the "--timeout" parameter when deploying a function via CLI, or the "timeoutInSeconds" parameter when using the deployFunction() API.
https://remotion.dev/docs/lambda/cli/functions#deploy",
name: "TimeoutError"
},
```

Could you shed some light on whether I need to do something to the inputProps, to make them accessible on DynamicComposition? 

Do I need to JSON.parse() the inputProp payload? Do I need to have a defaultProps passed to ```<Composition />```.

I also tried replacing the ```<Video />``` Element in _DynamicComposition.tsx_ with a vanila HTMLVIdeoElement ```<video />```. This removed the error, but then I received an error of infinite ```inputRange``` on the ```interpolate(...)``` function, in _Fade.tsx (Transition)_. This has led me to believe there's issues with inputProps.

_Copy of inputProps passed..._
```
inputProps: {
type: "payload",
payload: "{"segments":["{\"src\":\"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/video/45c9c167-8a72-42c4-ae8b-cb1bd4642124.mp4\",\"templateSrc\":\"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/template/c238620b-2340-45fe-8bc4-6076b1bbc538.txt\",\"id\":\"45c9c167-8a72-42c4-ae8b-cb1bd4642124\"}","{\"src\":\"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/video/e4e45ae3-24c4-4ec8-9939-bfa05d4ecf5a.mp4\",\"templateSrc\":\"https://storage.googleapis.com/577c83a4-19fd-4c01-b851-5bd4c15131e5/template/6c723a0b-f38b-4857-b093-1d3c7eaf5dee.txt\",\"id\":\"e4e45ae3-24c4-4ec8-9939-bfa05d4ecf5a\"}"],"metrics":{"fps":30,"compositionHeight":1920,"compositionWidth":1080,"aspectRatio":"9/16","maxLimit":5,"totalDurationInFrames":300,"segmentDurationInFrames":150,"totalDurationInSeconds":10}}"
},
```

The ```src``` key on the segments objects array, represents the ```<Video />``` src that should be playing.

Thank you for any help! 🙏

**Comment by JonnyBurger** [comment]
Solved on Discord: https://discord.com/channels/809501355504959528/817306238811111454/1123512728653402164
