### ISSUE TITLE
Render button Failed to render

### ISSUE THREAD

**Issue by winner106** [remotion-dev/remotion#2480]
After clicking the "Render" button, the code bundled, then an error occurs in the command line as follows:

```powershell
Node.js v18.13.0
PS K:\next-remotion> npx remotion preview src/remotion/index.ts  --config=src/remotion/remotion.config.ts           
Server ready - Local: http://localhost:3000, Network: http://172.16.200.36:3000
Built in 1317ms
To restart - Local: http://localhost:3000, Network: http://172.16.200.36:3000
╭─ Starting render 
│ (1/2) ╭───────────────────╮ Bundled code 1846ms
╰─  Failed to render
Error: Incompatible site: When visiting http://localhost:3001/index.html, a bundle was found, but one that is not compatible with this version of Remotion. Found version: undefined - Required version: 7. To resolve this error, please bundle and deploy again.
    at innerSetPropsAndEnv (K:\next-remotion\node_modules\.pnpm\@remotion+renderer@4.0.0_react-dom@18.2.0_react@18.2.0\node_modules\@remotion\renderer\dist\set-props-and-env.js:102:15)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async innerSelectComposition (K:\next-remotion\node_modules\.pnpm\@remotion+renderer@4.0.0_react-dom@18.2.0_react@18.2.0\node_modules\@remotion\renderer\dist\select-composition.js:25:5)
```

**Comment by winner106** [comment]
nothing is running on port 3001, In fact, I also attempted to configure multiple ports separately using the CLI, but encountered the same error. It was only after closing the preview that I could use the CLI to render the video.

```bash
> next-remotion@0.1.0 renderStill K:\next-remotion
> npx remotion still src/remotion/index.ts BarChart ./out/test.png --config=src/remotion/remotion.config.ts --log=verbose --bundle-cache=false --port=8888

Remotion root directory: K:\next-remotion
Applied configuration from K:\next-remotion\src\remotion\remotion.config.ts.
Checking if src/remotion/index.ts is the entry file
Bundled under C:\Users\ADMINI~1\AppData\Local\Temp\remotion-webpack-bundle-0Acf9R
Created directory for temporary files C:\Users\ADMINI~1\AppData\Local\Temp\remotion-v4-0-0-assetsiof8inl2ee

Error: Incompatible site: When visiting http://localhost:8888/index.html, a bundle was found, but one that is not compatible with this version of Remotion. Found version: undefined - Required version: 7. To resolve this error, please bundle and deploy again.
    at innerSetPropsAndEnv (K:\next-remotion\node_modules\.pnpm\@remotion+renderer@4.0.0_react-dom@18.2.0_react@18.2.0\node_modules\@remotion\renderer\dist\set-props-and-env.js:102:15)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async innerSelectComposition (K:\next-remotion\node_modules\.pnpm\@remotion+renderer@4.0.0_react-dom@18.2.0_react@18.2.0\node_modules\@remotion\renderer\dist\select-composition.js:25:5)
Cleaning up...
Cleanup done in 18ms
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by JonnyBurger** [comment]
#2526

Overhauled this part and you should get a way better error message.
Also fixed a bug which could cause it in the first place.
If the error prevails in v4.0.4, please file an issue with the new error message and we'll improve it from there!
