### ISSUE TITLE
Ubuntu Compositor crash: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by flesler** [remotion-dev/remotion#2579]
- OS: Ubuntu 20.04.2 LTS
- Node: v18.15.0
- Remotion: 4.0.5

When rendering it finishes successfully (the video is there and correct) but remotion crashes. Here's the error:
```
/project/node_modules/@remotion/renderer/dist/compositor/compositor.js:186
                throw new Error(`Compositor already quit: ${runningStatus.error}`);

Error: Compositor already quit: /project/node_modules/@remotion/compositor-linux-x64-gnu/compositor: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /project/node_modules/@remotion/compositor-linux-x64-gnu/compositor)
/project/node_modules/@remotion/compositor-linux-x64-gnu/compositor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /project/node_modules/@remotion/compositor-linux-x64-gnu/compositor)
/project/node_modules/@remotion/compositor-linux-x64-gnu/compositor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /project/node_modules/@remotion/compositor-linux-x64-gnu/compositor)
/project/node_modules/@remotion/compositor-linux-x64-gnu/compositor: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /project/node_modules/@remotion/compositor-linux-x64-gnu/compositor)

    at Object.finishCommands (/project/node_modules/@remotion/renderer/dist/compositor/compositor.js:186:23)
    at close (/project/node_modules/@remotion/renderer/dist/offthread-video-server.js:40:24)
    at close (/project/node_modules/@remotion/renderer/dist/serve-static.js:70:21)
    at Object.closeServer (/project/node_modules/@remotion/renderer/dist/prepare-server.js:63:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async processJobIfPossible (/project/node_modules/@remotion/cli/dist/preview-server/render-queue/queue.js:209:9)
```

I tried installing GLIBC 2.35, doesn't seem like I succeeded at solving this. But maybe this can be prevented? Since the rendering does work

**Comment by JonnyBurger** [comment]
This is true, from 4.0 on, there is a minimum system requirement of Libc (we wrongly state in getting started and migration guide that it is 2.34, fixing that now)

There is an issue open here: https://github.com/remotion-dev/remotion/issues/2439
