### ISSUE TITLE
Crash: Compositor error: Invalid data found when processing input

### ISSUE THREAD

**Issue by tzvc** [remotion-dev/remotion#2650]
Hey there,

Remotion version: [v4.0.12](https://github.com/remotion-dev/remotion/commit/e0fed0137b31b7d7b5d459f4387ed81d7f3dccd8)

I'm investigating a crash happening somewhat randomly (approx. 1/10) at render:

```
DEFAULT 2023-07-31T08:41:16.362365Z Error occurred Error: Compositor error: Invalid data found when processing input
DEFAULT 2023-07-31T08:41:16.362392Z 0: <compositor::errors::ErrorWithBacktrace as core::convert::From<ffmpeg_next::util::error::Error>>::from
DEFAULT 2023-07-31T08:41:16.362400Z 1: compositor::opened_stream::OpenedStream::get_frame
DEFAULT 2023-07-31T08:41:16.362406Z 2: compositor::commands::execute_command
DEFAULT 2023-07-31T08:41:16.362413Z 3: rayon_core::thread_pool::ThreadPool::install::{{closure}}
DEFAULT 2023-07-31T08:41:16.362421Z 4: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
DEFAULT 2023-07-31T08:41:16.362429Z 5: rayon_core::registry::WorkerThread::wait_until_cold
DEFAULT 2023-07-31T08:41:16.362437Z 6: std::sys_common::backtrace::__rust_begin_short_backtrace
DEFAULT 2023-07-31T08:41:16.362444Z 7: core::ops::function::FnOnce::call_once{{vtable.shim}}
DEFAULT 2023-07-31T08:41:16.362451Z 8: std::sys::unix::thread::Thread::new::thread_start
DEFAULT 2023-07-31T08:41:16.362457Z 9: <unknown>
DEFAULT 2023-07-31T08:41:16.362463Z 10: <unknown>
DEFAULT 2023-07-31T08:41:16.362472Z at onMessage (/usr/src/app/node_modules/@remotion/renderer/dist/compositor/compositor.js:56:47)
DEFAULT 2023-07-31T08:41:16.362479Z at processInput (/usr/src/app/node_modules/@remotion/renderer/dist/compositor/compositor.js:122:9)
DEFAULT 2023-07-31T08:41:16.362485Z at processInput (/usr/src/app/node_modules/@remotion/renderer/dist/compositor/compositor.js:125:9)
DEFAULT 2023-07-31T08:41:16.362491Z at processInput (/usr/src/app/node_modules/@remotion/renderer/dist/compositor/compositor.js:125:9)
DEFAULT 2023-07-31T08:41:16.362497Z at processInput (/usr/src/app/node_modules/@remotion/renderer/dist/compositor/compositor.js:125:9)
DEFAULT 2023-07-31T08:41:16.362502Z at processInput (/usr/src/app/node_modules/@remotion/renderer/dist/compositor/compositor.js:125:9)
DEFAULT 2023-07-31T08:41:16.362509Z at Socket.<anonymous> (/usr/src/app/node_modules/@remotion/renderer/dist/compositor/compositor.js:142:9)
DEFAULT 2023-07-31T08:41:16.362513Z at Socket.emit (node:events:513:28)
DEFAULT 2023-07-31T08:41:16.362519Z at addChunk (node:internal/streams/readable:324:12)
DEFAULT 2023-07-31T08:41:16.362524Z at readableAddChunk (node:internal/streams/readable:297:9)

```

I suspect `OffthreadVideo` being at the origin of this since it seems to come from ffmpeg, but it could also be at the final "stiching".

Has anyone experienced this crash?

**Comment by JonnyBurger** [comment]
Hi @tzvc!

This seems indicative of a corrupt video file.
Could you send the file to me for investigation? Either via upload, jonny@remotion.dev or on Discord (@jonnyburger).

I'll see if there is a better way to handle it or it should not crash at all.

**Comment by tzvc** [comment]
Was due to a corrupt video.

Verifiable by running `ffprobe input.mp4`
