### ISSUE TITLE
Failed to connect to socket /run/dbus/system_bus_socket

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2751]
From #2742 

Perhaps it is not related, but I am also encountering issue connecting to the browser sometimes (also randomely):

```
Timed out after 60000 ms while trying to connect to the browser! TimeoutError: Timed out after 60000 ms while trying to connect to the browser!
    at Timeout.onTimeout (/usr/src/app/node_modules/@remotion/renderer/dist/browser/BrowserRunner.js:243:20)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

Has anyone run into this? I'm not sure where to get started to investigate.

**Comment by JonnyBurger** [comment]
@tzvc Please, if you get this again with the new version, open an issue with the new error message!
We should then be able to debug this issue.

**Comment by tzvc** [comment]
I've updated to latest and ran it in prod again, here's the stack:

```
 [0817/190643.838808:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

    at Timeout.onTimeout (/usr/src/app/node_modules/@remotion/renderer/dist/browser/BrowserRunner.js:246:20)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) 
```

**Comment by JonnyBurger** [comment]
All of our Dockerfiles now include a command to install Dbus:

![Image](https://github.com/user-attachments/assets/0faf03fe-79d9-4e4f-ad30-4e3142fce519)
