### ISSUE TITLE
Chrome 116 on Ubuntu causes "Page crashed!" errors

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2879]

**Comment by JonnyBurger** [comment]
> {
        "type": "Error",
        "message": "Page crashed!",
        "stack": "Error: Page crashed!\n    at Page._Page_onTargetCrashed (/workdir/node_modules/@remotion/renderer/dist/browser/BrowserPage.js:276:24)\n    at /workdir/node_modules/@remotion/renderer/dist/browser/BrowserPage.js:112:94\n    at /workdir/node_modules/@remotion/renderer/dist/browser/mitt/index.js:39:17\n    at Array.forEach (<anonymous>)\n    at Object.emit (/workdir/node_modules/@remotion/renderer/dist/browser/mitt/index.js:38:18)\n    at CDPSession.emit (/workdir/node_modules/@remotion/renderer/dist/browser/EventEmitter.js:26:22)\n    at CDPSession._onMessage (/workdir/node_modules/@remotion/renderer/dist/browser/Connection.js:220:18)\n    at Connection._Connection_onMessage (/workdir/node_modules/@remotion/renderer/dist/browser/Connection.js:129:21)\n    at WebSocket.<anonymous> (/workdir/node_modules/@remotion/renderer/dist/browser/NodeWebSocketTransport.js:68:32)\n    at WebSocket.onMessage (/workdir/node_modules/@remotion/renderer/node_modules/ws/lib/event-target.js:199:18)"
}


> I'm running into the "Page crashed!" Chrome issue now too.
Running Remotion on a node:18.17.0 docker container which I believe is Debian.
Installing google-chrome-stable into the container

> Container runs in AWS Fargate on 16 vCPUs, 120GB RAM
> Also tried 4 vCPUs and 30GB of RAM to implicitly reduce concurrency (From performance observations, I've made the assumption that remotion spins up a separate chrome tab for each core available? Please correct me if not)
> I dont set concurrency manually. (Hm, I'll try setting up with the 16 cpu, 120gb again but specifically explicitly set concucrrency to something lower like 8)
> It's not particularly slow in the preview but sometimes the video playback lags behind the div overlay renders

> Remotion app renders an <OffThreadVideo> as well as backdrop-filter: blur() overlays
> Videos range in size but are typically around 2-4 GB

**Comment by JonnyBurger** [comment]
I think this is a false diagnostic. Not been able to prove this is a problem.
The problem has more likely been that os.freemem() and os.cpus() was called inside a Docker container on a Kubernetes cluster, leading to very high concurrency due to a bug. This issue has been fully solved as of 4.0.37.
