### ISSUE TITLE
Symbolicating minified error message... A delayRender() "Loading <Img> with src=http://localhost:3001/proxy?src=http%3A%2F%2Flocalhost%3A3000%2FnewBusiness.mAn error occurred while rendering frame 0:ut not cleared after 28000ms. See https://remotion.dev/docs/timeout for hel  Error  A delayRender() "Loading <Img> with src=http://localhost:3001/proxy?src=http%3A%2F%2Flocalhost%3A3000%2FnewBusiness.mp4&time=1.6&imageFormat=jpeg" was called but not cleared after 28000ms. 

### ISSUE THREAD

**Issue by idkblogs** [remotion-dev/remotion#2895]
I am getting the same errors on emotion while `npm run build`, Plz help me to solve this.

An error occurred:
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\browser\DOMWorld.js:156:34)
    at DOMWorld.waitForFunction (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\browser\DOMWorld.js:106:26)
    at waitForReady (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\seek-to-frame.js:21:25)
    at seekToFrame (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\seek-to-frame.js:52:36)
    at renderFrameWithOptionToReject (E:\PROJECTS\URL_TO_VIDEO_ALL\video-maker\node_modules\@remotion\renderer\dist\render-frames.js:166:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
    
    
    
    It is happening when I add a long video, I tried the above-provided workaround for the moment ie. `cd assets && npx serve` but it is still not working.
    
    
    
    Here are some pieces of my codes:
    
   ```
 
    import {AbsoluteFill, OffthreadVideo, staticFile} from 'remotion';
import {
	VIDEO_RESOLTION_WIDTH,
	VIDEO_RESOLTION_HEIGHT,
} from '../../constants/constant';

export const VideoWithText: React.FC<{
	link: any;
	delay: number;
	startFrom?: number;
	endAt?: number;
	videoSpeed?: number;
	isMuted?: boolean;
	opacity?: number;
	loop?: false;
	videoObject: any;
}> = ({
	videoObject,
	delay,
	link,
	startFrom,
	endAt,
	videoSpeed,
	isMuted = true,
	opacity = 1,
	loop,
}) => {
	const {
		videoWidth = VIDEO_RESOLTION_WIDTH,
		videoHeight = VIDEO_RESOLTION_HEIGHT,
		marginTop = '0px',
		marginLeft = '0px',
		videoBorderWidth,
		videoBorderColor,
		videoRadius,
		volume,
	} = videoObject;
	// const loacFileUrl = staticFile(link);
	const loacFileUrl = link;

	return (
		<AbsoluteFill>
			<OffthreadVideo
				src={loacFileUrl}
				style={{
					opacity,
					width: videoWidth,
					height: videoHeight,
					padding: '0px',
					marginLeft: marginLeft,
					marginTop: marginTop,
					border: `${videoBorderWidth} solid ${videoBorderColor}`,
					borderRadius: videoRadius,
				}}
				startFrom={startFrom}
				endAt={endAt}
				playbackRate={videoSpeed}
				muted={isMuted}
				volume={volume}
			/>
		</AbsoluteFill>
	);
};

```
    

**Earlier I was using `delayRender()` but I tried to comment on that code, still I getting error:**

```

import {useEffect, useState} from 'react';
import {
	Composition,
	// continueRender,
	// delayRender,
	getInputProps,
} from 'remotion';
import {getDuration} from '../utils/fetch-msgs';
import {Story} from './Story';
import {
	FRAME_PER_SECOND,
	CONTENTS_LENGTH,
	VIDEO_RESOLTION_WIDTH,
	VIDEO_RESOLTION_HEIGHT,
	CONFIG_BLOG_CONTENTS,
} from '../constants/constant';

const {
	global: {TOTAL_VIDEO_DURATION_IN_FRAMES},
} = CONFIG_BLOG_CONTENTS;

export const RemotionVideo: React.FC = () => {
	const props = getInputProps();
	// const [handle] = useState(() => delayRender("Getting duration..."));
	const [duration, setDuration] = useState<number | null>(1000);
	const [apiResponse, setApiResponse] = useState<object | null>({});

	useEffect(
		() => {
			getDuration(CONTENTS_LENGTH).then(({entrance, response}) => {
				setDuration(Math.floor(entrance));
				setApiResponse(response);
				// continueRender(handle);
			});
		},
		[
			// handle
		]
	);


	return (
		<>
			<Composition
				id="Story"
				component={Story}
				durationInFrames={TOTAL_VIDEO_DURATION_IN_FRAMES}
				fps={FRAME_PER_SECOND}
				width={VIDEO_RESOLTION_WIDTH - 10}
				height={VIDEO_RESOLTION_HEIGHT - 10}
				defaultProps={{
					messageIds: '',
					apiResponse,
				}}
			/>
		</>
	);
};
```

**Now I am not using delayRender() in their codes and getting the error:**

```

(1/3) ╭───────────────────╮ Bundled code 2622ms
Entry point = src\index.tsx (argument passed - found in cwd), Composition = Story (Passed as argument), Codec = h264 (derived from out name), Output = results/16Sept_StartCompany0924.mp4
(2/3)                       Rendering frames (6x) 0/3620
    + ╭───────────────────╮ Downloading 2 files                                                                      
(3/3)                       Encoding video 0/3620
Symbolicating minified error message...
A delayRender() "Loading <Img> with src=http://localhost:3001/proxy?src=http%3A%2F%2Flocalhost%3A3000%2FnewBusiness.mAn error occurred while rendering frame 0:ut not cleared after 28000ms. See https://remotion.dev/docs/timeout for hel
 Error  A delayRender() "Loading <Img> with src=http://localhost:3001/proxy?src=http%3A%2F%2Flocalhost%3A3000%2FnewBusiness.mp4&time=1.6&imageFormat=jpeg" was called but not cleared after 28000ms. See https://remotion.dev/docs/timeout for help.

at node_modules/@remotion/bundler/node_modules/remotion/dist/cjs/delay-render.js:41
39 │         ]
40 │             .filter(truthy_js_1.truthy)
41 │             .join(' ');
42 │         throw new Error(message);
43 │     }, timeoutToUse);
44 │ }


🕧 The delayRender() call is located at:

at node_modules/@remotion/bundler/node_modules/remotion/dist/cjs/delay-render.js:27
25 │ const handle = Math.random();
26 │ handles.push(handle);
27 │ const called = (_b = (_a = Error().stack) === null || _a === void 0 ? void 0 : _a.replace(/^Error/g, '')) !== null && _b !== void 0 ? _b : '';
28 │ if ((0, get_environment_js_1.getRemotionEnvironment)() === 'rendering') {
29 │     const timeoutToUse = typeof window === 'undefined'
30 │         ? defaultTimeout

at node_modules/@remotion/bundler/node_modules/remotion/dist/cjs/Img.js:62
60 │     return;
61 │ }
62 │ const newHandle = (0, delay_render_js_1.delayRender)('Loading <Img> with src=' + src);
63 │ const { current } = imageRef;
64 │ const onComplete = () => {
65 │     var _a, _b, _c, _d;
at Rj (node_modules/react-dom/cjs/react-dom.production.min.js:244)
at lk (node_modules/react-dom/cjs/react-dom.production.min.js:261)
at jk (node_modules/react-dom/cjs/react-dom.production.min.js:260)
at jk (node_modules/react-dom/cjs/react-dom.production.min.js:260)
at ik (node_modules/react-dom/cjs/react-dom.production.min.js:259)
at Xk (node_modules/react-dom/cjs/react-dom.production.min.js:283)
at Qk (node_modules/react-dom/cjs/react-dom.production.min.js:281)
at Hk (node_modules/react-dom/cjs/react-dom.production.min.js:270)
at (node_modules/@remotion/bundler/node_modules/remotion/dist/cjs/delay-render.js:42)

💡 Get help for this issue at https://remotion.dev/docs/timeout
```
 
    

**Please help**

**Comment by idkblogs** [comment]
I also tried reducing concurrency but still not working. Earlier It was working but suddenly stopped working without any code change. I also gone through doc **https://www.remotion.dev/docs/timeou**t  but no luck.

**Comment by idkblogs** [comment]
Here is my package.json file:

```
{
	"name": "videoMaker",
	"version": "1.0.0",
	"description": "My Remotion video",
	"scripts": {
		"start": "remotion preview src/index.tsx",
		"build": "remotion render src/index.tsx Story results/16Sept_StartCompany0924.mp4",
		"upgrade": "remotion upgrade",
		"server": "ts-node server.tsx",
		"test": "eslint src --ext ts,tsx,js,jsx && tsc"
	},
	"repository": {},
	"license": "UNLICENSED",
	"dependencies": {
		"@remotion/cli": "3.0.0",
		"@remotion/shapes": "4.0.29",
		"@types/react": "18.2.7",
		"@types/react-dom": "18.2.4",
		"@types/styled-components": "5.1.26",
		"date-fns": "2.30.0",
		"express": "4.18.2",
		"lodash": "4.17.21",
		"polished": "4.2.2",
		"qs": "6.11.2",
		"react": "18.2.0",
		"react-dom": "18.0.0",
		"remotion": "3.0.0",
		"styled-components": "5.3.11"
	}
}




```

**Comment by JonnyBurger** [comment]
Hi @idkblogs! This is probably because the video file is so big that it takes longer than 30sec to download.
OffthreadVideo needs to download the whole video before the render can progress.

If you think that is the problem as well, you can increase the timeout using --timeout in the CLI or the timeoutInMilliseconds parameter.

**Comment by JonnyBurger** [comment]
I assume this is the reason and am closing this issue.
