### ISSUE TITLE
Rendering OffthreadVideo with m3u8 results in "Compositor error: Invalid data found when processing input"

### ISSUE THREAD

**Issue by sydneypalumbo** [remotion-dev/remotion#2930]
Hi there! I'm currently trying to use m3u8 files (from mux.com) as the `src` of `<OffthreadVideo />` with remotion v4.0.19 but getting the following error during rendering. I thought this would be supported with ffmpeg, but is it not possible to use m3u8 with OffthreadVideo? Here's an [example file](https://stream.mux.com/xQF2bL9915XLtxl9BHv7F8xUpOSaDDqAvgi702otut7g.m3u8), which doesn't seem to be corrupt. Thanks so much in advance for your help!

```
>  [compositor] [FFmpeg] Statistics: 2196 bytes read, 0 seeks
>  Error occurred Error: Compositor error: Invalid data found when processing input
>     0: std::backtrace::Backtrace::force_capture 
>     1: <compositor::errors::ErrorWithBacktrace as core::convert::From<ffmpeg_next::util::error::Error>>::from
>     2: compositor::opened_stream::open_stream
>     3: compositor::opened_video_manager::OpenedVideoManager::get_video
>     4: compositor::commands::execute_command
>     5: rayon_core::thread_pool::ThreadPool::install::{{closure}}
>     6: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
>     7: rayon_core::registry::WorkerThread::wait_until_cold
>     8: std::sys_common::backtrace::__rust_begin_short_backtrace
>     9: core::ops::function::FnOnce::call_once{{vtable.shim}}
>    10: std::sys::unix::thread::Thread::new::thread_start
>    11: __pthread_joiner_wake
>      at onMessage (/.../node_modules/@remotion/renderer/dist/compositor/compositor.js:56:47)
>      at processInput (/.../node_modules/@remotion/renderer/dist/compositor/compositor.js:122:9)
>      at Socket.<anonymous> (/.../node_modules/@remotion/renderer/dist/compositor/compositor.js:142:9)
>      at Socket.emit (node:events:514:28)
>      at Socket.emit (node:domain:489:12)
>      at addChunk (node:internal/streams/readable:324:12)
>      at readableAddChunk (node:internal/streams/readable:297:9)
>      at Socket.Readable.push (node:internal/streams/readable:234:10)
>      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by JonnyBurger** [comment]
Thanks a lot!

Actually, there is no explicit documentation on which codecs are supported by OffthreadVideo. I am fixing that with #2934.

We'll also add a FFmpeg binary which supports HLS in the next version after which we can assess whether this file can be supported.

**Comment by JonnyBurger** [comment]
The new version now throws a different error and it seems like it will take significant effort to support M3U8.

Until we sort it out, I recommend to enable MP4 files on Mux and use those to render!

**Comment by sydneypalumbo** [comment]
@JonnyBurger sounds good, thanks again!

**Comment by mjdavidson** [comment]
@JonnyBurger we're also very keen to use HLS with `<OffthreadVideo />`, to preview video edits on our front-end. How far away do you think support for this will be?

**Comment by JonnyBurger** [comment]
@mjdavidson If you just need it in the preview / Remotion Player, you can probably add hls.js to get it working!

For rendering, we need to parse the HLS format and download only the specific parts before feeding it to OffthreadVideo.

The scariest part is the HLS spec which seems quite long. I don't see a suitable library for JS/Rust that we can get working quickly, so I don't see it happening soon.

**Comment by mjdavidson** [comment]
@JonnyBurger yep, when we render the final video we have access to a normalized mp4 video so we will use that. We already use `hls.js` in our React project for our normal video player. How do you propose linking `hls.js` to the Remotion video component?

**Comment by JonnyBurger** [comment]
@mjdavidson Sure, I added a snippet for it here: https://www.remotion.dev/docs/miscellaneous/snippets/hls

Only tested some very basic cases though.

**Comment by rmanalan** [comment]
I got this working pretty well today. I did end up adding a few optimizations to the `useEffect` in the guide:

```ts
  useEffect(() => {
    if (!src) {
      throw new Error('src is required')
    }

    const hls = new Hls({
      enableWorker: !isSafari(),
      lowLatencyMode: true,
      backBufferLength: 20,
      startLevel: 4,
      maxBufferLength: 5,
      maxMaxBufferLength: 5,
    })
    if (hls) {
      hls.on(Hls.Events.MANIFEST_PARSED, () => {
        hls.startLoad(startFrom)
      })
      hls.attachMedia(videoRef.current!)
      hls.loadSource(src)
    }

    return () => {
      hls.destroy()
    }
  }, [src])
  ```

**Comment by JonnyBurger** [comment]
@rmanalan Thanks for sharing! Putting this back into the docs: https://github.com/remotion-dev/remotion/pull/3155

**Comment by JonnyBurger** [comment]
By "will not render", I meant actually turning the video into an MP4, which I think is true. I'll clarify it as well.

**Comment by tslater** [comment]
@JonnyBurger Can you give a little more detail as to what errors you're getting or what you need to feed to the component? I'd like to try my hand at getting hls to work if you can give me the context.

**Comment by JonnyBurger** [comment]
@tslater I don't know the errors I got specifically, I just know that the native `<video>` tag doesn't support HLS by default and the FFmpeg C library doesn't recognize a .m3u8 as media like other video files. 

It is just unknown to them which is why it doesn't work right now.

**Comment by urbit-pilled** [comment]
Looks like something I can fix, I'll give it a try /attempt #2930

**Comment by JonnyBurger** [comment]
I think this is a really difficult issue to solve (at least for me 😄)

Do you have a plan on how to proceed? @urbit-pilled 

(The bounty was not created by us nor someone we know!)

**Comment by feliciien** [comment]
@sydneypalumbo Hello can you tell me what command? Did you run for having this ">  [compositor] [FFmpeg] Statistics: 2196 bytes read, 0 seeks
>  Error occurred Error: Compositor error: Invalid data found when processing input
>     0: std::backtrace::Backtrace::force_capture 
>     1: <compositor::errors::ErrorWithBacktrace as core::convert::From<ffmpeg_next::util::error::Error>>:: from
>     2: compositor::opened_stream::open_stream
>     3: compositor::opened_video_manager::OpenedVideoManager::get_video
>     4: compositor::commands::execute_command
>     5: rayon_core::thread_pool::ThreadPool::install::{{closure}}
>     6: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
>     7: rayon_core::registry::WorkerThread::wait_until_cold
>     8: std::sys_common::backtrace::__rust_begin_short_backtrace
>     9: core::ops::function::FnOnce::call_once{{vtable.shim}}
>    10: std::sys::unix::thread::Thread::new::thread_start
>    11: __pthread_joiner_wake
>      at onMessage (/.../node_modules/@remotion/renderer/dist/compositor/compositor.js:56:47)
>      at processInput (/.../node_modules/@remotion/renderer/dist/compositor/compositor.js:122:9)
>      at Socket.<anonymous> (/.../node_modules/@remotion/renderer/dist/compositor/compositor.js:142:9)
>      at Socket.emit (node:events:514:28)
>      at Socket.emit (node:domain:489:12)
>      at addChunk (node:internal/streams/readable:324:12)
>      at readableAddChunk (node:internal/streams/readable:297:9)
>      at Socket.Readable.push (node:internal/streams/readable:234:10)
>      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)" and where I want to reproduce the same error so it will be more easy for me to fix it

**Comment by feliciien** [comment]
I want to reproduce the same error on my editor

**Comment by 0018akhil** [comment]
@JonnyBurger

Is there a time limit to a video?

There should be a time limit to the video because we can play live stream via the **.m3u8** link.

I tried playing a video, it gets the packets(segments) in the network tab but the video player only plays the video once it gets all the packets(segments).

**Comment by JonnyBurger** [comment]
We have not put out this bounty and don't have a clear path towards solving this issue.
This is very hard, don't attempt it unless you know exactly what to do!

**Comment by Asmitpadia** [comment]
Instead of usign OffthreadVideo we can use a library for react video.js and can also inspect that the m3u8 file is correct or not. If you are interested we can try this

**Comment by JonnyBurger** [comment]
A small update on this, we are building a new Video tag in the future that is based on @remotion/media-parser and WebCodecs.

This one will support HLS and eventually replace OffthreadVideo.

**Comment by tsejerome** [comment]
This is awesome @JonnyBurger we are looking forward to it :D Happy to put some bounty as well

**Comment by hunxjunedo** [comment]
hey @tsejerome , no need for that, we already have a basic prototype ready, will be merged soon as an experimental feature! #5522

**Comment by tsejerome** [comment]
> hey @tsejerome , no need for that, we already have a basic prototype ready, will be merged soon as an experimental feature! #5522 
Looking forward!

**Comment by JonnyBurger** [comment]
Our current status on this:

We have shipped a new `<Video>` tag https://www.remotion.dev/docs/media/video which is based on Mediabunny.

We're now gold sponsors of Mediabunny. While we do not control the roadmap, we have defined HLS support as a feature that is in scope for Mediabunny and that will be developed in the mid-term.

From what I understand, the current priority is Mediabunny 2.0 and afterwards HLS is high up on priorities.

**Comment by JonnyBurger** [comment]
There is no plan to add HLS support for OffthreadVideo - we're focusing on the new `<Video>` tag.

**Comment by JonnyBurger** [comment]
Update: https://github.com/Vanilagy/mediabunny/issues/89#issuecomment-3711279534

**Comment by CuboYe** [comment]
I can take this one. I’ll prototype HLS support for the Video component in a backward-compatible way, with format handling notes and validation steps in the PR.

**Comment by JonnyBurger** [comment]
@CuboYe Please don't, as you can read in this PR, this is already WIP in Mediabunny

**Comment by JonnyBurger** [comment]
In 4.0.454, we are finally supporting HLS! https://www.remotion.dev/docs/hls
Courtesy of @Vanilagy's awesome Mediabunny library 🎉
