### ISSUE TITLE
Port busy issue with PowerShell in VS Code on Windows

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3084]
```
╭─ Starting render 
│ (1/3) ╭───────────────────╮ Bundled code 2122ms
╰─  Failed to render
Error: Error while getting compositions: Tried to go to http://localhost:3001/index.html and verify that it is a Remotion project by checking if window.getStaticCompositions is defined.
However, the function was undefined, which indicates that this is not a valid Remotion project. Please check the URL you passed.
The page loaded contained the following markup:

Does this look like a foreign page? If so, try to stop this server.
    at innerSetPropsAndEnv (Z:\vscode\soundiclyvideomaker\node_modules\.pnpm\@remotion+renderer@4.0.57_react-dom@18.2.0_react@18.2.0\node_modules\@remotion\renderer\dist\set-props-and-env.js:102:15)        
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async setPropsAndEnv (Z:\vscode\soundiclyvideomaker\node_modules\.pnpm\@remotion+renderer@4.0.57_react-dom@18.2.0_react@18.2.0\node_modules\@remotion\renderer\dist\set-props-and-env.js:155:20)       
    at async innerSelectComposition (Z:\vscode\soundiclyvideomaker\node_modules\.pnpm\@remotion+renderer@4.0.57_react-dom@18.2.0_react@18.2.0\node_modules\@remotion\renderer\dist\select-composition.js:27:5)
```

> Running pnpm exec remotion render VideoComp out/testvideo.mp4 inside vscode's terminal window (using powershell, I'm on Windows) will throw that error even setting a port manually that's 100% free (I think it has to do with port forwarding from the new feature, or with code tunnels). Running it from a powershell with vscode closed works.

**Comment by JonnyBurger** [comment]
The problem for this is the Console Ninja extension intercepting the Remotion server. They fixed the problem on their side.
