### ISSUE TITLE
registerRoot() was called more than once because of hot reloading in preview mode

### ISSUE THREAD

**Issue by hustLer2k** [remotion-dev/remotion#3278]
# Bug Report 🐛

In a next.js application i get `error - Error: registerRoot() was called more than once.
    at registerRoot (file:///C:/Users/Administrator/Documents/reps/momentum-video/node_modules/.pnpm/remotion@4.0.75_react-dom@18.2.0_react@18.2.0/node_modules/remotion/dist/esm/index.mjs:3405:15)
    at eval (webpack-internal:///../../packages/video/src/index.ts:14:55) {
  page: '/preview'
}` when hot reloading the page.

**Comment by JonnyBurger** [comment]
See this note:

> registerRoot() should live in a file that is separate from the list of compositions. This is because when using React Fast Refresh, all the code in the file that gets refreshed gets executed again, however, this function should only be called once.

https://www.remotion.dev/docs/register-root

I recommend to structure it like in the Hello World template, creating a separate file just for registerRoot().
