### ISSUE TITLE
Feature Request - Render Still using python SDK

### ISSUE THREAD

**Issue by kacperadach** [remotion-dev/remotion#3295]
# Feature Request 🛍️

I would like to use python to render a still on Lambda

**Comment by JonnyBurger** [comment]
- This is how renderMediaOnLambda() is implemented in Node: https://github.com/remotion-dev/remotion/blob/9bd9ac21a76ba67b4dddf0549d77fee60e23d02c/packages/lambda/src/api/render-media-on-lambda.ts#L155
- This is how render_media_on_lambda is implemented in Python: https://github.com/remotion-dev/remotion/blob/9bd9ac21a76ba67b4dddf0549d77fee60e23d02c/packages/lambda-python/remotion_lambda/remotionclient.py#L128
- This is how renderStillOnLambda() is implemented in Node: https://github.com/remotion-dev/remotion/blob/9bd9ac21a76ba67b4dddf0549d77fee60e23d02c/packages/lambda/src/api/render-still-on-lambda.ts#L63
- **Task:** Implement render_still_on_lambda in Python!


## Requirements

- Should be able to make a still render on Lambda
- The API of render_media_on_lambda and render_still_on_lambda should be uniform
- Add a test in `packages/lambda-python/tests`, analogue to render_media_on_lambda
- Add a new example to the docs: `https://github.com/remotion-dev/remotion/blob/9bd9ac21a76ba67b4dddf0549d77fee60e23d02c/packages/docs/docs/lambda/python.md#L32`
- The streaming feature (`onInit` callback) does **not** have to be implemented. 
- Input props compressions does **not** have to be implemented - analogue to render_media_on_lambda

## Bounty

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 175

**Comment by JonnyBurger** [comment]
good luck @alexfernandez803!

**Comment by JonnyBurger** [comment]
will ship in the next release!

**Comment by kacperadach** [comment]
Found a bug:

Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/routers/tasks.py", line 119, in render_thumbnail
    render_response = client.render_still_on_lambda(render_params)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/remotion_lambda/remotionclient.py", line 210, in render_still_on_lambda
    accrued_so_far=body_object['estimatedPrice']['accruedSoFar'],
KeyError: 'estimatedPrice'

**Comment by JonnyBurger** [comment]
@kacperadach Does it work well? I got an email about a potential error, not sure if we did something wrong
