### ISSUE TITLE
Render fails with "AuthorizationHeaderMalformed" due to hardcoded region in custom credentials.

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#3474]
[From message posted on Discord by **jl982**](https://discord.com/channels/809501355504959528/1207006049748520990/1207006049748520990)
----
I'm rendering media on lambda, and want to save the output to a custom s3 location. Per documentation (https://www.remotion.dev/docs/lambda/custom-destination#saving-to-another-cloud), I passed this to `renderMediaOnLambda`:

```
  outName: {
    key: "my-output",
    bucketName: "output-bucket",
    s3OutputProvider: {
      endpoint: "https://s3.us-west-1.amazonaws.com",
      accessKeyId: "<AWS_ACCESS_KEY_ID>",
      secretAccessKey: "<AWS_SECRET_ACCESS_KEY>",
    },
  },
```
However, the render fails with `AuthorizationHeaderMalformed`
```
  {
    "chunk": null,
    "frame": null,
    "name": "AuthorizationHeaderMalformed",
    "stack": "AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-1'\n    at throwDefaultError (/var/task/index.js:45783:24)\n    at /var/task/index.js:45793:39\n    at de_PutObjectCommandError (/var/task/index.js:62352:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /var/task/index.js:42726:24\n    at async /var/task/index.js:40347:22\n    at async /var/task/index.js:43978:42\n    at async /var/task/index.js:68017:22\n    at async /var/task/index.js:37619:26\n    at async tryLambdaWriteFile (/var/task/index.js:146705:3)",
    "type": "stitcher",
    "isFatal": true,
    "tmpDir": null,
    "attempt": 1,
    "totalAttempts": 1,
    "willRetry": false,
    "message": "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-1'",
    "explanation": null,
    "s3Location": "..."
  }
```

Looking at the source code, the cause appears to be due to the region being hardcoded to `us-east-1` for custom credentials: https://github.com/remotion-dev/remotion/blob/main/packages/lambda/src/shared/aws-clients.ts#L206

Is this a bug? Happy to open a PR to fix it. Otherwise, please suggest how I can fix this problem.

**Comment by JonnyBurger** [comment]
The bug was different, it is explained in the thread what actually happened
