### ISSUE TITLE
`window.location.origin` breaking URL when used inside of iframe

### ISSUE THREAD

**Issue by par5ul1** [remotion-dev/remotion#3502]
When loading a `<Player />` from an iframe with a srcdoc, `window.location.origin` will return `'null'`. This is used, [among other functions](https://github.com/search?q=repo:remotion-dev/remotion+window.location.origin&type=code), in `getAbsoluteSrc`.

This issue was first observed by me when attempting to use the `<Video />` component with an absolute url. The project renders properly via SSR, but in my sandboxed iframe environment, I got the following error:

```
Uncaught TypeError: Failed to construct 'URL': Invalid base URL
    at getAbsoluteSrc (index.mjs:177:12)
    at durationReducer (index.mjs:1237:18)
    at updateReducer (react-dom.development.js:16664:22)
    at Object.useReducer (react-dom.development.js:17898:16)
    at useReducer (react.development.js:1627:21)
    at DurationsContextProvider (index.mjs:1250:88)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19583:20)
    at beginWork (react-dom.development.js:21596:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
```

Proposed fix is to use `window.origin` instead of `window.location.origin`. See: https://html.spec.whatwg.org/multipage/webappapis.html#dom-origin-dev
> Developers are strongly encouraged to use self.origin over location.origin. The former returns the [origin](https://html.spec.whatwg.org/multipage/browsers.html#concept-origin) of the environment, the latter of the URL of the environment.

**Comment by par5ul1** [comment]
I have opened a PR to address this, and I tested this to the best of my ability.

**Comment by mateusrachid** [comment]
Also happens when the document has been loaded with the `file:` protocol.

Minimal reproduction: https://github.com/mateusrachid/remotion-location-origin-issue
