### ISSUE TITLE
Whisper.cpp subtitle generation for TikTok video format not working

### ISSUE THREAD

**Issue by coderscoveyt** [remotion-dev/remotion#3560]
# Bug Report 🐛

Hello, recently started using this technology for making YouTube videos and I can safely say I'm absolutely a fan.

I usually use the Tailwind template, where I have encountered no issues.

However, I get the following error, when I try to work with a TikTok format:

The error is reproducible by just making a TikTok format template and running the command to generate subtitles as instructed, namely `node sub.mjs`. The whisper installs, but the subtitles do not get generated.

```console
Error: Command failed: main.exe -f C:\YouTube\short\temp\sample-video.wav --output-file C:\YouTube\short\public\_sample-video --output-json --max-len 1 -m C:\YouTube\short\whisper.cpp\ggml-medium.en.bin
whisper_init_from_file_with_params_no_state: loading model from 'C:\YouTube\short\whisper.cpp\ggml-medium.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 4 (medium)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      CPU buffer size =  1533.52 MB
whisper_model_load: model size    = 1533.14 MB
whisper_init_state: kv self size  =  132.12 MB
whisper_init_state: kv cross size =  147.46 MB
whisper_init_state: compute buffer (conv)   =   25.61 MB
whisper_init_state: compute buffer (encode) =  170.28 MB
whisper_init_state: compute buffer (cross)  =    7.85 MB
whisper_init_state: compute buffer (decode) =   98.31 MB

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0 |

main: processing 'C:\YouTube\short\temp\sample-video.wav' (191467 samples, 12.0 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...


    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at subFile (file:///C:/YouTube/short/sub.mjs:93:2)
    at processVideo (file:///C:/YouTube/short/sub.mjs:144:8)
    at processDirectory (file:///C:/YouTube/short/sub.mjs:164:10)
    at file:///C:/YouTube/short/sub.mjs:176:8 {
  status: 3221225501,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1632) [Uint8Array] [
      119, 104, 105, 115, 112, 101, 114,  95, 105, 110, 105, 116,
       95, 102, 114, 111, 109,  95, 102, 105, 108, 101,  95, 119,
      105, 116, 104,  95, 112,  97, 114,  97, 109, 115,  95, 110,
      111,  95, 115, 116,  97, 116, 101,  58,  32, 108, 111,  97,
      100, 105, 110, 103,  32, 109, 111, 100, 101, 108,  32, 102,
      114, 111, 109,  32,  39,  67,  58,  92,  89, 111, 117,  84,
      117,  98, 101,  92, 115, 104, 111, 114, 116,  92, 119, 104,
      105, 115, 112, 101, 114,  46,  99, 112, 112,  92, 103, 103,
      109, 108,  45, 109,
      ... 1532 more items
    ]
  ],
  pid: 17504,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1632) [Uint8Array] [
    119, 104, 105, 115, 112, 101, 114,  95, 105, 110, 105, 116,
     95, 102, 114, 111, 109,  95, 102, 105, 108, 101,  95, 119,
    105, 116, 104,  95, 112,  97, 114,  97, 109, 115,  95, 110,
    111,  95, 115, 116,  97, 116, 101,  58,  32, 108, 111,  97,
    100, 105, 110, 103,  32, 109, 111, 100, 101, 108,  32, 102,
    114, 111, 109,  32,  39,  67,  58,  92,  89, 111, 117,  84,
    117,  98, 101,  92, 115, 104, 111, 114, 116,  92, 119, 104,
    105, 115, 112, 101, 114,  46,  99, 112, 112,  92, 103, 103,
    109, 108,  45, 109,
    ... 1532 more items
  ]
}

Node.js v21.6.2
```

**Comment by JonnyBurger** [comment]
Thanks for reporting!

It seems like we swallow the error unfortunately.
Can you run `cd whisper.cpp`, then `main.exe -f C:\YouTube\short\temp\sample-video.wav --output-file C:\YouTube\short\public\_sample-video --output-json --max-len 1 -m C:\YouTube\short\whisper.cpp\ggml-medium.en.bin`

and paste the output in here?

**Comment by coderscoveyt** [comment]
Sure!
This seems to get rid of the error, however nothing else happens.
Perhaps it's still running in the background (like & in Linux)?
Anyways, here's the output:

```console
PS C:\YouTube\short\whisper.cpp> ./main.exe -f C:\YouTube\short\temp\sample-video.wav --output-file C:\YouTube\short\public\_sample-video --output-json --max-len 1 -m C:\YouTube\short\whisper.cpp\ggml-medium.en.bin
whisper_init_from_file_with_params_no_state: loading model from 'C:\YouTube\short\whisper.cpp\ggml-medium.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 4 (medium)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      CPU buffer size =  1533.52 MB
whisper_model_load: model size    = 1533.14 MB
whisper_init_state: kv self size  =  132.12 MB
whisper_init_state: kv cross size =  147.46 MB
whisper_init_state: compute buffer (conv)   =   25.61 MB
whisper_init_state: compute buffer (encode) =  170.28 MB
whisper_init_state: compute buffer (cross)  =    7.85 MB
whisper_init_state: compute buffer (decode) =   98.31 MB

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0 |

main: processing 'C:\YouTube\short\temp\sample-video.wav' (191467 samples, 12.0 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...
PS C:\YouTube\short\whisper.cpp>
```

**Comment by JonnyBurger** [comment]
Does it not yield a JSON file?

I tried it on Windows 11. Works as well and results in a JSON file.

I ChatGPT'd the error code `3221225501`:

> The exit status 3221225501 in Windows corresponds to an application crash, likely due to an access violation error (commonly seen as 0xC0000005). This error typically indicates that the program tried to access memory that it shouldn't have, possibly due to a bug in the program or some kind of incompatible operation.

Which means that Whisper.cpp crashes on your system, maybe due to a hardware-specific problem.

If you can reproduce a with Whisper.cpp specifically, you should file it at Whisper.cpp, maybe also look at similar issues https://github.com/ggerganov/whisper.cpp/issues?q=sigsegv
