### ISSUE TITLE
FontLoadingError: Failed to check if font is ready

### ISSUE THREAD

**Issue by enesozturk** [remotion-dev/remotion#366]
Hi Jonny, thanks for great library 🙌🏽 
I was trying to create an animation and render it. Firstly I rendered the initial Hello World example. That was totally ok. After that I created my animation example. When I try to render it I got the following error. **(FontLoadingError)** Do you have any idea what can cause it? I already deleted all other components in my repo.

```js
📦 (1/3) [====================] Bundled code 1440ms
🖼  (2/3) [===                 ] Rendering frames (2x) 36/240
The following error occurred when trying to render frame 37:
FontLoadingError: Failed to check if font is ready (5000ms timeout exceeded)
    at Object.<anonymous> (http://localhost:3000/bundle.js:9226:17)
    at Generator.throw (<anonymous>)
    at rejected (http://localhost:3000/bundle.js:9190:26)
error Command failed with exit code 1.
```

Here is my components: 
<details>
<summary>`index.ts`</summary>

```js
import {registerRoot} from 'remotion';
import {RemotionVideo} from './Video';

registerRoot(RemotionVideo);
```

</details>

<details>
<summary>`Video.tsx`</summary>

```js
import {Composition} from 'remotion';
import {HelloWorld} from './HelloWorld';

export const RemotionVideo: React.FC = () => {
  return (
      <Composition
          id="HelloWorld"
          component={HelloWorld}
          durationInFrames={240}
          fps={120}
          width={1920}
          height={1920}
    />
  );
};
```
</details>

<details>
<summary>`HelloWorld.tsx`</summary>

```js
import {Color} from 'framer';
import {RectangleItem} from './HelloWorld/RectangleItem';

const ITEMS = [1, 2, 3, 4, 5, 6, 7, 8];
const FIRST_ITEM_SIZE = 800;
const COLOR_MAX_RANGE = 80;
const PARTITION_SIZE = FIRST_ITEM_SIZE / ITEMS.length;
const COLOR_PARTITION_SIZE = COLOR_MAX_RANGE / ITEMS.length;
const darkBlue = Color('#8f132b');

export const HelloWorld: React.FC = () => {
  const items = useState(() => {
    return new Array(10).fill(true).map((_, index) => {
      const size = FIRST_ITEM_SIZE - PARTITION_SIZE * index;
      
      const reversedIndex = ITEMS.length - index;
      const colorSize = COLOR_MAX_RANGE - COLOR_PARTITION_SIZE * reversedIndex;
      const blue = Color.lighten(darkBlue, colorSize);
      const transparent = Color.alpha(blue, 0.5);
      
      return (
          <RectangleItem
	      size={size}
	      color={Color.toRgbString(transparent)}
	      itemDelay={index * 5}
          />
      );
    });
  });
  
  return <div style={{flex: 1, backgroundColor: 'rgb(34,34,34)'}}>{items}</div>;
};
```

</details>

<details>
<summary>`RectangleItem.tsx`</summary>

```js
import {spring, useCurrentFrame, useVideoConfig} from 'remotion';

const animationDelay = 120;

export const RectangleItem: React.FC<{
  size: number;
  color: string;
  itemDelay: number;
}> = ({size = 600, color = 'red', itemDelay = 0}) => {
  const videoConfig = useVideoConfig();
  const frame = useCurrentFrame();
  
  const up = spring({
    frame: frame - itemDelay,
    config: {mass: 0.5},
    from: 1,
    to: 2,
    fps: videoConfig.fps,
  });
  
  const down = spring({
    frame: frame - animationDelay - itemDelay,
    config: {
    mass: 0.5,
    },
    from: 2,
    to: 1,
    fps: videoConfig.fps,
  });
  
  const value = frame < animationDelay / 2 ? up : frame <= animationDelay ? 2 : down;
  
  const scale = value;
  const radius = (size / 2) * (value - 0.9);
  const rotate = 90 * value;
  
  return (
    <div
      style={{
      position: 'absolute',
      left: '50%',
      top: '50%',
      width: size,
      height: size,
      backgroundColor: color,
      borderRadius: radius,
      transform: `translate(-50%, -50%) rotate(${rotate}deg) scale(${scale})`}}
    />
  );
};

```

</details>

**Comment by enesozturk** [comment]
Looks like issue is because of the **framer** package. I was using framer for dynamic colors. This is not a good solution but I did not have to use framer and changed it with [color](https://www.npmjs.com/package/color-scheme) for my example project. Closing the issue. ✌🏽

**Comment by Iamshankhadeep** [comment]
@enesozturk  I was trying to look into `framer` code to dig if `Color` does weird things but sad `framer` is not open sourced.

**Comment by enesozturk** [comment]
Oh thanks for trying help man ✋🏽, I actually did not even noticed if they open sourced or not. 🙂 Just used them several times and creating animations with framer motion is easy. But Framer is out this time 🙂
