### ISSUE TITLE
 Remotion Cloud Run Service Does Not Respond After Update to v4.0.148

### ISSUE THREAD

**Issue by ahmersaud** [remotion-dev/remotion#3805]
After updating my service to v4.0.148, I am no longer receiving a response when I call the service from my client. I attempted to invoke it from the CLI and received the following message:

```
Loaded env file from H:\remotion\project\.env.
Cloud Run Service URL = https://my-remotioncloud-run-link.run.app
Region = us-east1
Type = media
Composition = Plain
Codec = h264
Output Bucket = remotioncloudrun-bucket
Output File = out.mp4
Output File Privacy = public 
```

Despite this, there was no indication of rendering progress. I checked the designated storage location to see if the file had been rendered, but I could not find any output.

I'm unsure how to proceed to rectify this issue. Should I redeploy the service? Any guidance or troubleshooting steps would be greatly appreciated.

p.s : in this example i am only rendering a 30 second video with captions.

**Comment by ahmersaud** [comment]
after waiting for a long while i recieved this error:

An error occurred in the cli:
```
Error: upstream request timeout
    at Gaxios._request (H:\remotion\node_modules\gaxios\build\src\gaxios.js:140:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IdTokenClient.requestAsync (H:\remotion\node_modules\google-auth-library\build\src\auth\oauth2client.js:382:18)
    at async internalRenderMediaOnCloudrunRaw (H:\remotion\node_modules\@remotion\cloudrun\dist\api\render-media-on-cloudrun.js:67:26)
    at async H:\remotion\node_modules\@remotion\renderer\dist\wrap-with-error-handling.js:8:20
    at async renderCommand (H:\remotion\node_modules\@remotion\cloudrun\dist\cli\commands\render\index.js:191:17)
    at async Object.executeCommand (H:\remotion\node_modules\@remotion\cloudrun\dist\cli\index.js:50:9)
    at async cloudrunCommand (H:\remotion\node_modules\@remotion\cli\dist\cloudrun-command.js:12:9)
    at async cli (H:\remotion\node_modules\@remotion\cli\dist\index.js:86:13)
```

**Comment by ssijak** [comment]
@JonnyBurger same issue with the latest versions

**Comment by JonnyBurger** [comment]
I will release a new version to day with the fix: https://github.com/remotion-dev/remotion/pull/4169

We are now pinning the Chrome version so hopefully no further disruptions. Sorry about that!
