### ISSUE TITLE
CLI: npx remotion lambda commands fail after update

### ISSUE THREAD

**Issue by oskareke** [remotion-dev/remotion#3852]
I recently updated to 4.0.153 and I can no longer deploy my site to lambda. I get the error below (and the same happens for all npx remotion lambda (...) commands. I have my env vars set up (using REMOTION_AWS_ACCESS_KEY_ID & REMOTION_AWS_SECRET_ACCESS_KEY) and it was working fine prior to updating. Did anything change that I should know of, or do you have any other ideas?

`npx remotion lambda sites create remotion/index.ts --site-name=my-video

An error occurred:
Error: EISDIR: illegal operation on a directory, read
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at readFileSync (node:fs:441:19)
    at isLikelyToHaveAwsProfile (/Users/admin/www/remotionProject/node_modules/@remotion/lambda/dist/shared/is-likely-to-have-aws-profile.js:39:43)
    at checkCredentials (/Users/admin/www/remotionProject/node_modules/@remotion/lambda/dist/shared/check-credentials.js:24:70)
    at matchCommand (/Users/admin/www/remotionProject/node_modules/@remotion/lambda/dist/cli/index.js:45:50)
    at Object.executeCommand (/Users/admin/www/remotionProject/node_modules/@remotion/lambda/dist/cli/index.js:103:15)
    at lambdaCommand (/Users/admin/www/remotionProject/node_modules/@remotion/cli/dist/lambda-command.js:12:31)
    at cli (/Users/admin/www/remotionProject/node_modules/@remotion/cli/dist/index.js:85:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by oskareke** [comment]
Update: I switched to using the credentials file (~/.aws/credentials) instead and it's working. Closing this.

**Comment by JonnyBurger** [comment]
This error would occur if `~/.aws/credentials` is a folder instead of a file. Is this something that AWS supports?

**Comment by oskareke** [comment]
No idea - I think I messed up somehow, so problem is/was on my end. Thanks for looking.
