### ISSUE TITLE
Error when building Remotion project on Mac Air M1

### ISSUE THREAD

**Issue by try-to-fly** [remotion-dev/remotion#3862]
I encountered the following error while using Remotion on my Mac Air M1:

**Steps to reproduce:**
1. Run the command: `pnpm create video`
2. Choose the template: Hello World
3. Run the command: `pnpm build`

**Error message:**
```
Error: Command was killed with SIGABRT (Aborted): /private/tmp/my-video/node_modules/.pnpm/@remotion+compositor-darwin-arm64@4.0.157/node_modules/@remotion/compositor-darwin-arm64/ffmpeg -f lavfi -i anullsrc=r=48000 -c:a pcm_s16le -t 5 -ar 48000 /var/folders/fy/x7hf9wdn41g3tjlfnvgs9r1r0000gn/T/remotion-v4-0-157-assetstpreupbblb/remotion-audio-preprocessing/merged.wav
dyld[3613]: Symbol not found: _av_get_channel_layout
  Referenced from: <99DB3E84-E93D-3D2B-A902-636F3BB2C22A> /private/tmp/my-video/node_modules/.pnpm/@remotion+compositor-darwin-arm64@4.0.157/node_modules/@remotion/compositor-darwin-arm64/ffmpeg
  Expected in:     <B417A657-2A9E-3395-8D13-6686418E25E2> /opt/homebrew/Cellar/ffmpeg/7.0_1/lib/libavfilter.10.1.100.dylib
    at makeError (/private/tmp/my-video/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/private/tmp/my-video/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createSilentAudio (/private/tmp/my-video/node_modules/.pnpm/@remotion+renderer@4.0.157_react-dom@18.0.0_react@18.0.0/node_modules/@remotion/renderer/dist/create-silent-audio.js:7:5)
    at async mergeAudioTrackUnlimited (/private/tmp/my-video/node_modules/.pnpm/@remotion+renderer@4.0.157_react-dom@18.0.0_react@18.0.0/node_modules/@remotion/renderer/dist/merge-audio-track.js:21:9)
```

**Remotion version:** 4.0.157
**Operating system:** Mac Air M1 14.4.1

**Comment by JonnyBurger** [comment]
Thanks for reporting!
Your DYLD_LIBRARY_PATH might be messed up, but Remotion can handle it better too.

**Comment by try-to-fly** [comment]
There is still this error when using the new version(4.0.159) of Remotion.


`Error: Command was killed with SIGABRT (Aborted): /private/tmp/aa2/node_modules/.pnpm/@remotion+compositor-darwin-arm64@4.0.159/node_modules/@remotion/compositor-darwin-arm64/ffmpeg -f lavfi -i anullsrc=r=48000 -c:a pcm_s16le -t 5 -ar 48000 /var/folders/fy/x7hf9wdn41g3tjlfnvgs9r1r0000gn/T/remotion-v4-0-159-assetsfbwj7r8wtt/remotion-audio-preprocessing/merged.wav
dyld[38988]: Symbol not found: _av_get_channel_layout
  Referenced from: <99DB3E84-E93D-3D2B-A902-636F3BB2C22A> /private/tmp/aa2/node_modules/.pnpm/@remotion+compositor-darwin-arm64@4.0.159/node_modules/@remotion/compositor-darwin-arm64/ffmpeg
  Expected in:     <B417A657-2A9E-3395-8D13-6686418E25E2> /opt/homebrew/Cellar/ffmpeg/7.0_1/lib/libavfilter.10.1.100.dylib
    at makeError (/private/tmp/aa2/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/private/tmp/aa2/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createSilentAudio (/private/tmp/aa2/node_modules/.pnpm/@remotion+renderer@4.0.159_react-dom@18.3.1_react@18.3.1/node_modules/@remotion/renderer/dist/create-silent-audio.js:7:5)
    at async mergeAudioTrackUnlimited (/private/tmp/aa2/node_modules/.pnpm/@remotion+renderer@4.0.159_react-dom@18.3.1_react@18.3.1/node_modules/@remotion/renderer/dist/merge-audio-track.js:21:9)
`

**Comment by JonnyBurger** [comment]
Hmm that's super weird, I need to diagnose why it happens on your system

Can you post the output of `echo $PATH` and `echo $DYLD_LIBRARY_PATH`?

**Comment by try-to-fly** [comment]
The output results of these commands are as follows.

```
echo $PATH
/Users/smile/.asdf/shims:/Users/smile/.asdf/bin:/Users/smile/.config/tmux/plugins/t-smart-tmux-session-manager/bin:/Users/smile/.tmux/plugins/t-smart-tmux-session-manager/bin:/Users/smile/.local/bin:/Users/smile/.fly/bin:/Users/smile/.bun/bin:/Users/smile/.nvm/versions/node/v20.12.0/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/smile/.config/tmux/plugins/t-smart-tmux-session-manager/bin:/Users/smile/.tmux/plugins/t-smart-tmux-session-manager/bin:/Users/smile/.local/bin:/Users/smile/miniconda3/bin:/Users/smile/miniconda3/condabin:/Users/smile/Library/pnpm:/Users/smile/.fly/bin:/Users/smile/.bun/bin:/Users/smile/.nvm/versions/node/v20.12.0/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/smile/.cargo/bin:/Applications/kitty.app/Contents/MacOS:/Users/smile/.orbstack/bin:/opt/homebrew/opt/fzf/bin:/Users/smile/.orbstack/bin
```

```
echo $DYLD_LIBRARY_PATH
/opt/homebrew/lib/
```

**Comment by JonnyBurger** [comment]
Giving it another try!
