### ISSUE TITLE
renderMediaOnLambda Defaults to h264-ts Instead of Specified h264 Codec

### ISSUE THREAD

**Issue by maxmillionbeatz** [remotion-dev/remotion#3879]
Despite specifying the h264 codec in the renderMediaOnLambda function, the output defaults to h264-ts. I tried audioCodec "aac" and "mp3" but the issue persists.

Steps to reproduce: 

set x264Preset in combination with codec h264.

```typescript
const response = await renderMediaOnLambda({
    region: 'us-east-1',
    crf: 23,
     audioCodec: "mp3",
    functionName: 'remotionAwsLambdaFunctionName',
    composition: "MyComp",
    codec: "h264",
    x264Preset: "fast",
    logLevel: "error",
    concurrencyPerLambda: 2,
    serveUrl: 'remotionAwsServeurl',
    outName: `out.mp4`,
    downloadBehavior: { type: "download", fileName: "download.mp4" },
    inputProps: { ...input },
});

```

Error message:
You have set a x264 preset but the codec is "h264-ts". Set the codec to "h264" or remove the Preset profile.

**Comment by maxmillionbeatz** [comment]
```json
{
"message":"You have set a x264 preset but the codec is \"h264-ts\". Set the codec to \"h264\" or remove the Preset profile.",
"stack":"TypeError: You have set a x264 preset but the codec is \"h264-ts\". Set the codec to \"h264\" or remove the Preset profile.\n at validateSelectedCodecAndPresetCombination (/var/task/index.js:34474:15)\n at internalRenderMediaRaw (/var/task/index.js:36522:67)\n at Object.internalRenderMedia (/var/task/index.js:32410:24)\n at /var/task/index.js:144614:39\n at new Promise (<anonymous>)\n at renderHandler (/var/task/index.js:144613:9)\n at async rendererHandler (/var/task/index.js:144818:5)\n at async innerHandler (/var/task/index.js:145389:22)\n at async Runtime.routine [as handler] (/var/task/index.js:145452:5)\n at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1118:26)",
"frame":null,
"explanation":null
}
```

**Comment by JonnyBurger** [comment]
It's intended, with h264-ts we can concatenate the videos on Lambda.
It wasn't intended that x264 isn't supported anymore, will be fixed in the next version!
