### ISSUE TITLE
Broken doc links

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#4128]
```
Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /blog:
   -> linking to /docs/composition#composition
- Broken anchor on source page path = /blog/1-1:
   -> linking to /docs/data-fetching#telling-remotion-to-wait-until-the-data-is-loaded
- Broken anchor on source page path = /blog/1-2:
   -> linking to /docs/cli#flags
- Broken anchor on source page path = /blog/1-4:
   -> linking to /docs/cli#flags
- Broken anchor on source page path = /blog/1-5:
   -> linking to /docs/#additional-step-for-linux-users
- Broken anchor on source page path = /blog/2-0:
   -> linking to /blog/#remotionmedia-utils-package
   -> linking to /docs/cli#flags
- Broken anchor on source page path = /blog/2-2:
   -> linking to /docs/video/#controlling-playback-speed
   -> linking to /docs/player/#showvolumecontrols
   -> linking to /docs/player/#getvolume
   -> linking to /docs/player/#setvolume
   -> linking to /docs/player/#mute
   -> linking to /docs/player/#unmute
   -> linking to /docs/player/#ismuted
   -> linking to /docs/player/#timeupdate
   -> linking to /docs/player/#seeked
   -> linking to /docs/player/#clicktoplay
   -> linking to /docs/player/#doubleclicktofullscreen
- Broken anchor on source page path = /blog/4-0:
   -> linking to /docs/composition#composition
- Broken anchor on source page path = /blog/page/2:
   -> linking to /docs/video/#controlling-playback-speed
   -> linking to /docs/player/#showvolumecontrols
   -> linking to /docs/player/#getvolume
   -> linking to /docs/player/#setvolume
   -> linking to /docs/player/#mute
   -> linking to /docs/player/#unmute
   -> linking to /docs/player/#ismuted
   -> linking to /docs/player/#timeupdate
   -> linking to /docs/player/#seeked
   -> linking to /docs/player/#clicktoplay
   -> linking to /docs/player/#doubleclicktofullscreen
   -> linking to /blog/#remotionmedia-utils-package
   -> linking to /docs/cli#flags
   -> linking to /docs/#additional-step-for-linux-users
- Broken anchor on source page path = /blog/page/3:
   -> linking to /docs/data-fetching#telling-remotion-to-wait-until-the-data-is-loaded
- Broken anchor on source page path = /docs/4-0-migration:
   -> linking to /docs/cli#setvideoimageformat
   -> linking to /docs/cli#setstillimageformat
   -> linking to /docs/offthreadvideo#imageformat-availablefrom-v3022-
- Broken anchor on source page path = /docs/chromium-flags:
   -> linking to /docs/renderer/get-compositions#disablewebsecurity
   -> linking to /docs/renderer/get-compositions#ignorecertificateerrors
   -> linking to /docs/renderer/get-compositions#headless
   -> linking to /docs/renderer/get-compositions#gl
   -> linking to /docs/renderer/get-compositions#useragent
- Broken anchor on source page path = /docs/cli/benchmark:
   -> linking to /docs/cli/render#--ffprobe-executable
- Broken anchor on source page path = /docs/cli/compositions:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
   -> linking to /docs/config#setPort
   -> linking to /docs/config#setFfmpegExecutable
   -> linking to /docs/config#setFfprobeExecutable
- Broken anchor on source page path = /docs/cli/render:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
   -> linking to /docs/config#enforceaudiotrack
   -> linking to /docs/config#setFfmpegExecutable
   -> linking to /docs/config#setFfprobeExecutable
- Broken anchor on source page path = /docs/cli/still:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
   -> linking to /docs/config#setPort
   -> linking to /docs/config#setFfmpegExecutable
   -> linking to /docs/config#setFfprobeExecutable
- Broken anchor on source page path = /docs/cli/studio:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/cloudrun/cli/render:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/cloudrun/cli/still:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
   -> linking to /docs/config#setStillImageFormat
- Broken anchor on source page path = /docs/cloudrun/rendermediaoncloudrun:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/cloudrun/renderstilloncloudrun:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/config:
   -> linking to /docs/cli/render#--ffprobe-executable
- Broken anchor on source page path = /docs/easing:
   -> linking to /docs/easing#in
- Broken anchor on source page path = /docs/encoding:
   -> linking to /docs/cli#flags
- Broken anchor on source page path = /docs/gl-options:
   -> linking to /docs/renderer/get-compositions#gl
- Broken anchor on source page path = /docs/iframe:
   -> linking to #maxretries (resolved as: /docs/iframe#maxretries)
- Broken anchor on source page path = /docs/lambda/changelog:
   -> linking to /docs/lambda/setup#5-add-permissions-to-your-user
- Broken anchor on source page path = /docs/lambda/cli/compositions:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/lambda/cli/render:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
   -> linking to #outname (resolved as: /docs/lambda/cli/render#outname)
- Broken anchor on source page path = /docs/lambda/cli/still:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/lambda/custom-destination:
   -> linking to /docs/lambda/downloadmedia#s3outputprovider
   -> linking to /docs/lambda/getrenderprogress#s3outputprovider
- Broken anchor on source page path = /docs/lambda/custom-layers:
   -> linking to /docs/lambda/setup#5-add-permissions-to-your-user
- Broken anchor on source page path = /docs/lambda/getcompositionsonlambda:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/lambda/getrenderprogress:
   -> linking to /docs/artifacts#using-rendermediaonlambda
- Broken anchor on source page path = /docs/lambda/optimizing-cost:
   -> linking to /docs/parameterized-rendering#input-props
- Broken anchor on source page path = /docs/lambda/rendermediaonlambda:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/lambda/renderstillonlambda:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
   -> linking to /docs/artifacts#using-renderstillonlambda
- Broken anchor on source page path = /docs/passing-props:
   -> linking to /docs/composition#component
- Broken anchor on source page path = /docs/player/buffer-state:
   -> linking to /docs/offthreadvideo#pausewhenloading
- Broken anchor on source page path = /docs/player/player:
   -> linking to /docs/player/buffer-state#state-management
   -> linking to #setmuted (resolved as: /docs/player/player#setmuted)
   -> linking to #seek (resolved as: /docs/player/player#seek)
- Broken anchor on source page path = /docs/player/premounting:
   -> linking to /docs/offthreadvideo#pausewhenloading
- Broken anchor on source page path = /docs/player/thumbnail:
   -> linking to /docs/player/buffer-state#state-management
- Broken anchor on source page path = /docs/renderer/get-compositions:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/renderer/render-frames:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/renderer/render-media:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/renderer/render-still:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/renderer/select-composition:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-the-cli
- Broken anchor on source page path = /docs/ssr:
   -> linking to /docs/parameterized-rendering#passing-input-props-in-github-actions
- Broken anchor on source page path = /docs/ssr-legacy:
   -> linking to /docs#installation
   -> linking to /docs/parameterized-rendering#passing-props-in-github-actions
- Broken anchor on source page path = /docs/stills:
   -> linking to /docs/cli/#npx-remotion-still
- Broken anchor on source page path = /docs/target-closed:
   -> linking to /docs/#additional-step-for-linux-users
- Broken anchor on source page path = /docs/terminology:
   -> linking to /docs/terminology/composition#composition
- Broken anchor on source page path = /docs/terminology/composition:
   -> linking to #composition (resolved as: /docs/terminology/composition#composition)
   -> linking to /docs/the-fundamentals#defining-compositions
- Broken anchor on source page path = /docs/terminology/input-props:
   -> linking to #composition (resolved as: /docs/terminology/input-props#composition)
   -> linking to #remotion-studio (resolved as: /docs/terminology/input-props#remotion-studio)
   -> linking to #remotion-player (resolved as: /docs/terminology/input-props#remotion-player)
- Broken anchor on source page path = /docs/troubleshooting/player-flicker:
   -> linking to /docs/img/#pausewhenbuffering
- Broken anchor on source page path = /docs/video-vs-offthreadvideo:
   -> linking to /docs/offthreadvideo#transparent-
- Broken anchor on source page path = /docs/wrong-composition-mount:
   -> linking to /docs/player/player#component
```

**Comment by kaf-lamed-beyt** [comment]
I'd love to get on this @JonnyBurger, if no one is on it at the moment. Any pointers on where to start?

**Comment by JonnyBurger** [comment]
Yes @kaf-lamed-beyt! Thank you! 🙌🏼

This output is from https://www.remotion.dev/docs/contributing/#running-documentation and then running `pnpm run build-docs`

Those pages all exist but the titles have changed or moved into other pages. for example /docs/player -> /docs/player#api.
Or each terminology entry has a separate page now for example.

Every one you can find would be appreciated!

**Comment by kaf-lamed-beyt** [comment]
Huh! I see. I get on it and let you know it goes @JonnyBurger.

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger , apologies for not giving you any feedback yet. I've been stuck with work.

**Comment by kaf-lamed-beyt** [comment]
@JonnyBurger, I keep running into this error. 

```bash
docs git:(main) pnpm start

> docs@4.0.188 start /home/seven/Documents/codes/oss/remotion/packages/docs
> docusaurus start --host 0.0.0.0

[INFO] Starting the development server...

[ERROR] Error: Docusaurus could not load module at path "/home/seven/Documents/codes/oss/remotion/packages/docs/shiki.js"
Cause: Cannot find module '/home/seven/Documents/codes/oss/remotion/packages/docs/node_modules/@remotion/docusaurus-plugin/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at loadFreshModule (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+utils@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80/node_modules/@docusaurus/utils/lib/moduleUtils.js:36:15)
    at loadPreset (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80_eslint@8.56.0_react-dom@18.3._be7iepoldlavxye2ljnsnby2bu/node_modules/@docusaurus/core/lib/server/plugins/presets.js:33:65)
    at Array.map (<anonymous>)
    at loadPresets (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80_eslint@8.56.0_react-dom@18.3._be7iepoldlavxye2ljnsnby2bu/node_modules/@docusaurus/core/lib/server/plugins/presets.js:37:53)
    at loadPluginConfigs (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80_eslint@8.56.0_react-dom@18.3._be7iepoldlavxye2ljnsnby2bu/node_modules/@docusaurus/core/lib/server/plugins/configs.js:71:52)
    at initPlugins (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80_eslint@8.56.0_react-dom@18.3._be7iepoldlavxye2ljnsnby2bu/node_modules/@docusaurus/core/lib/server/plugins/init.js:42:65)
    at /home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80_eslint@8.56.0_react-dom@18.3._be7iepoldlavxye2ljnsnby2bu/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:136:112
    at Object.async (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80_eslint@8.56.0_react-dom@18.3._be7iepoldlavxye2ljnsnby2bu/node_modules/@docusaurus/core/lib/utils.js:36:47)
    at /home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80_eslint@8.56.0_react-dom@18.3._be7iepoldlavxye2ljnsnby2bu/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:136:61
    at Object.async (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+core@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80_eslint@8.56.0_react-dom@18.3._be7iepoldlavxye2ljnsnby2bu/node_modules/@docusaurus/core/lib/utils.js:36:47) {
  [cause]: Error: Cannot find module '/home/seven/Documents/codes/oss/remotion/packages/docs/node_modules/@remotion/docusaurus-plugin/dist/index.js'. Please verify that the package.json has a valid "main" entry
      at tryPackage (node:internal/modules/cjs/loader:444:19)
      at Module._findPath (node:internal/modules/cjs/loader:715:18)
      at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
      at Function.resolve (node:internal/modules/helpers:187:19)
      at _resolve (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:241814)
      at jiti (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:244531)
      at /home/seven/Documents/codes/oss/remotion/packages/docs/shiki.js:1:94
      at evalModule (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
      at jiti (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
      at loadFreshModule (/home/seven/Documents/codes/oss/remotion/node_modules/.pnpm/@docusaurus+utils@3.4.0_@docusaurus+types@3.4.0_@swc+core@1.3.80/node_modules/@docusaurus/utils/lib/moduleUtils.js:33:16) {
    code: 'MODULE_NOT_FOUND',
    path: '/home/seven/Documents/codes/oss/remotion/packages/docs/node_modules/@remotion/docusaurus-plugin/package.json',
    requestPath: '@remotion/docusaurus-plugin'
  }
}
[INFO] Docusaurus version: 3.4.0
Node version: v20.10.0
```

**Comment by kaf-lamed-beyt** [comment]
I think it is somewhat related to a shikiji dependency. 

I did `pnpm install` in the root dir, and even when I cd into `~packages/docs`

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Did you also run `pnpm build` after you ran `pnpm i` in the root?

**Comment by kaf-lamed-beyt** [comment]
Oh no. I didn't lemme do that now

**Comment by kaf-lamed-beyt** [comment]
I may have to install bun @JonnyBurger? 

```bash
n:build: > remotion@4.0.189 build /home/seven/Documents/codes/oss/remotion/packages/core
remotion:build: > bun --env-file=../.env.bundle bundle.ts
remotion:build: 
remotion:build: sh: 1: bun: not found
remotion:build:  ELIFECYCLE  Command failed.
remotion:build: ERROR: command finished with error: command (/home/seven/Documents/codes/oss/remotion/packages/core) /home/seven/.nvm/versions/node/v20.10.0/bin/pnpm run build exited (1)
@remotion/layout-utils:build: 
remotion#build: command (/home/seven/Documents/codes/oss/remotion/packages/core) /home/seven/.nvm/versions/node/v20.10.0/bin/pnpm run build exited (1)

 Tasks:    1 successful, 3 total
Cached:    0 cached, 3 total
  Time:    1m37.9s 
Failed:    remotion#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Yes indeed! Here is a list of all steps you need to take: https://www.remotion.dev/docs/contributing

**Comment by kaf-lamed-beyt** [comment]
Huh! True. I'll check this. 

Thank you!

**Comment by JonnyBurger** [comment]
Hi @kaf-lamed-beyt,

sorry to hear about your internet situation 😌

It's not super urgent, always appreciated when somebody takes time to improve something.
I'll leave you assigned but don't feel the pressure to do it!

**Comment by kaf-lamed-beyt** [comment]
Ayy! Thank you, @JonnyBurger!
