### ISSUE TITLE
Unable to use TransitionSeries inside Remotion Player component

### ISSUE THREAD

**Issue by tonyabracadabra** [remotion-dev/remotion#4153]
## Version
Everything upgraded in `4.0.191`

## Minimum viable code:

```tsx
import { Player } from "@remotion/player";
import { TransitionSeries } from "@remotion/transitions";

const Video = () => (
    <TransitionSeries>
        <TransitionSeries.Sequence durationInFrames={30}>
            <div style={{background: 'red', width: '100%', height: '100%'}} />
        </TransitionSeries.Sequence>
        <TransitionSeries.Sequence durationInFrames={30}>
            <div style={{background: 'blue', width: '100%', height: '100%'}} />
        </TransitionSeries.Sequence>
    </TransitionSeries>
);

const App = () => (
    <Player
        component={Video}
        durationInFrames={60}
        compositionWidth={1920}
        compositionHeight={1080}
        fps={30}
    />
);
```

## Errors
```bash
Error: No video config found. Likely reasons:-- You are probably calling useVideoConfig() from outside the component passed to <Player />. See https://www.remotion.dev/docs/player/examples for how to set up the Player correctly.-- You have multiple versions of Remotion installed which causes the React context to get lost.
    at useVideoConfig (index.mjs:1487:19)
    at RegularSequenceRefForwardingFunction (index.mjs:1633:25)
    at react-stack-bottom-frame (react-dom-client.development.js:22216:20)
    at renderWithHooks (react-dom-client.development.js:5763:22)
    at updateForwardRef (react-dom-client.development.js:7640:19)
    at beginWork (react-dom-client.development.js:9848:18)
    at runWithFiberInDEV (react-dom-client.development.js:554:16)
    at performUnitOfWork (react-dom-client.development.js:14923:22)
    at workLoopSync (react-dom-client.development.js:14773:41)
    at renderRootSync (react-dom-client.development.js:14751:11)
    at performConcurrentWorkOnRoot (react-dom-client.development.js:14236:11)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:44:48)
```

**Comment by JonnyBurger** [comment]
It looks fine, but you likely have a version mismatch between `remotion` and `@remotion/transitions`.
What does `npx remotion versions` say? (`@remotion/cli` is required for this)

**Comment by JonnyBurger** [comment]
Hmm, that could be a mixup between RSC as well

- what if you add "use client" at the top?
- try clearing the cache `rm -rf .next && npm run dev`

**Comment by JonnyBurger** [comment]
Thanks for reporting!
