### ISSUE TITLE
Deploy to AWS Lambda in `ap-southeast-5` Region Fails with Validation Error

### ISSUE THREAD

**Issue by sontl** [remotion-dev/remotion#4548]
#### Bug Report 🐛

**Description**  
Attempting to deploy to AWS Lambda in the `ap-southeast-5` (Malaysia) region results in a validation error. The error suggests that `ap-southeast-5` is not recognized as a valid AWS region. 

**Error Message**  
```
TypeError: ap-southeast-5 is not a valid AWS region. Must be one of: 
eu-central-1, eu-west-1, eu-west-2, eu-west-3, eu-south-1, eu-north-1, us-east-1, 
us-east-2, us-west-1, us-west-2, af-south-1, ap-south-1, ap-east-1, ap-southeast-1, 
ap-southeast-2, ap-northeast-1, ap-northeast-2, ap-northeast-3, ca-central-1, 
me-south-1, sa-east-1
    at validateAwsRegion (/path/to/remotion/lambda/dist/shared/validate-aws-region.js:7:15)
    at getAwsRegion (/path/to/remotion/lambda/dist/cli/get-aws-region.js:19:53)
    ...
```

**Steps to Reproduce**  
1. Configure Remotion Lambda deployment with the region set to `ap-southeast-5`.
2. Run the deployment command:  
   ```bash
   npx remotion lambda function deploy
   npx remotion lambda sites create remotion/index.ts --site-name=
   ```
3. Observe the error.

**Expected Behavior**  
Deployment should recognize `ap-southeast-5` as a valid AWS region and proceed without error.

**Actual Behavior**  
Deployment fails with a region validation error.

**Environment**  
- **Remotion Version:** [Provide your version here, e.g., `4.0.229`]  
- **Node.js Version:** [Provide your Node.js version, e.g., `18.x`]  
- **AWS CLI Version (if applicable):** [Provide your AWS CLI version, e.g., `2.x`]  
- **OS:** [Provide your OS details, e.g., macOS 13.5]

**Additional Information**  
- `ap-southeast-5` is a valid AWS region as per the AWS [[documentation](https://docs.aws.amazon.com/general/latest/gr/rande.html)](https://docs.aws.amazon.com/general/latest/gr/rande.html).
- This issue might stem from an outdated list of supported regions in the Remotion Lambda validation logic.

**Suggested Fix**  
Update the region validation logic in the `validate-aws-region.js` file to include `ap-southeast-5`.  

**Workaround**  
No known workaround at the moment.

Thank you for looking into this issue! Let me know if additional details or logs are required.

**Comment by JonnyBurger** [comment]
We can consider adding support for this region in the future

At the moment we don't store the prices for it and have not deployed the Lambda Layers, this is the reason we only support a few regions at a time

See the regions supported: https://www.remotion.dev/docs/lambda/region-selection

**Comment by sontl** [comment]
Yeah,  hope it can be supported soon because it's cheapest pricing compare to others

**Comment by peeyush14goyal** [comment]
Is this issue parked for now?
