### ISSUE TITLE
Error parsing/converting from webm from MediaRecorder

### ISSUE THREAD

**Issue by dodgerbluelab** [remotion-dev/remotion#4559]
A key frame is required?
https://github.com/user-attachments/assets/9fb2e973-d761-41aa-a62e-550c612aad27

# Bug Report 🐛

I uploaded the attached webm file that I've created/recorded using a new MediaRecorder() of an animated canvas.
The error I get in the https://www.remotion.dev/convert interface is this:

DataError: Failed to execute 'decode' on 'VideoDecoder': A key frame is required after configure() or flush().
    at d (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:157476)
    at async https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:161559
    at async Object.onVideoSample (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:135988)
    at async Yi (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:130300)
    at async Tp (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:132444)
    at async ir (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:132111)
    at async sr (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:132843)
    at async Dr (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:133571)
    at async ir (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:131644)
    at async sr (https://www.remotion.dev/convert/assets/seo-BPyJEZHQ.js:1:132843)

Your tool looks promising, and looking forwards to a resolution. 
The file has not trouble being converted by Handbrake, which could be replaced if a fix could be archived.

Sincerely,
Jeppe

**Comment by JonnyBurger** [comment]
Hi Jeppe,

Just tried in Chrome, Safari and Firefox with all formats, seems to work for me!

Can you tell me which browser and which formats you selected?
Please also say which browser version since the bug doesn't seem completely obvious.

**Comment by dodgerbluelab** [comment]
Hi

Thanks for the quick reply.
It’s Version 131.0.6778.86 (Officiel version) (arm64) on MacBook Pro.

I uploaded the webm and attempted to convert to mp4.

**Comment by JonnyBurger** [comment]
Works for me!

MacBook Air M2

Downloaded https://github.com/user-attachments/assets/9fb2e973-d761-41aa-a62e-550c612aad27 and dragged it into remotion.dev/convert

Convert to MP4, default settings

Same version even: 131.0.6778.86

So I assume it works now, maybe since the PR I shipped yesterday!
If you can demonstrate an error, let me know.

**Comment by dodgerbluelab** [comment]
Yeah maybe your PR did something, because it works in my end too! 
Thx :)
