### ISSUE TITLE
Video fails to convert from MP4 to WebM

### ISSUE THREAD

**Issue by peterfox** [remotion-dev/remotion#4680]
The video in question (unable to upload it to GH)

https://drive.google.com/file/d/1kkaQlt-JWK-7g-MG44sFL484twectMxB/view?usp=sharing

The video was made via Google Earth Studio.

# Bug Report 🐛

Not much else to share beyond a copy of the conversion page

![Image](https://github.com/user-attachments/assets/06aad86d-9345-4600-93f8-2c97055b961b)

Error shown on the page:

```
DataError: Failed to execute 'decode' on 'VideoDecoder': A key frame is required after configure() or flush().
    at l (https://www.remotion.dev/convert/assets/flip-video-jnXNdiIr.js:2:14815)
    at async https://www.remotion.dev/convert/assets/flip-video-jnXNdiIr.js:2:19567
    at async Object.onVideoSample (https://www.remotion.dev/convert/assets/flip-video-jnXNdiIr.js:1:161346)
    at async br (https://www.remotion.dev/convert/assets/flip-video-jnXNdiIr.js:1:100685)
    at async xr (https://www.remotion.dev/convert/assets/flip-video-jnXNdiIr.js:1:119473)
    at async se (https://www.remotion.dev/convert/assets/flip-video-jnXNdiIr.js:1:124338)
    at async yu (https://www.remotion.dev/convert/assets/flip-video-jnXNdiIr.js:1:164849)
```

**Comment by JonnyBurger** [comment]
Thanks for reporting!
We need to lie to Chrome as it does not recognize some keyframes which are some 🙈
