### ISSUE TITLE
Error rendering in ubuntu

### ISSUE THREAD

**Issue by johann04** [remotion-dev/remotion#593]
My code:

```
			const tmpDir = path.join(__dirname, 'examples', companyId, videoName, 'frames');
			if (!fs.existsSync(tmpDir)) {
				fs.mkdirSync(tmpDir);
			}
			const {assetsInfo} = await renderFrames({
				config: video,
				webpackBundle: bundled,
				onStart: () => console.log('Rendering frames...'),
				onFrameUpdate: (f) => {
					if (f % 10 === 0) {
						console.log('Rendered frame' + f);
					}
				},
				parallelism: null,
				outputDir: tmpDir,
				inputProps: props,
				compositionId,
				imageFormat: 'jpeg',
			});

			const finalVideoOutput = path.join(__dirname, 'examples', companyId, videoName, 'example_' + lang + '.mp4');
			await stitchFramesToVideo({
				dir: tmpDir,
				force: true,
				fps: video.fps,
				height: video.height,
				width: video.width,
				outputLocation: finalVideoOutput,
				imageFormat: 'jpeg',
				assetsInfo,
			});
```

Fails after rendering the last frame and starting `stitchFramesToVideo`

```
TypeError: results.flat is not a function
    at convertAssetsToFileUrls (/opt/video-templates/server/node_modules/@remotion/renderer/src/assets/convert-assets-to-file-urls.ts:41:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The thing is... it works in my Mac OS, but fails when I try to run it on Linux.

**Comment by johann04** [comment]
It looks like remotion requires nodejs 13 or above... you should put that in the installation guide

**Comment by JonnyBurger** [comment]
I think the minimum version is 12.10.0 as mentioned in the setup docs (https://www.remotion.dev/docs)

Do you think that is wrong?
Also you should have gotten a warning if version requirement was not satisfied, if we need to fix that let us know!

**Comment by JonnyBurger** [comment]
Closing due to no response.
