### ISSUE TITLE
Can't compile on Linux : Error: Root has not been registered.

### ISSUE THREAD

**Issue by rnangia** [remotion-dev/remotion#872]
Can't compile on Linux
      **remotion.js reads**
```
import Neon from './script.js';
import React from 'react';
import {Composition} from 'remotion';
class RemotionVideo extends React.Component {
 render() {
   return (
           <Composition
            id="NeonArk"
            component={<Neon intensity={2} blur={10} />}
            durationInFrames={30}
            fps={30}
            width={1920}
            height={1080}
          />
        );
 }
}

export default RemotionVideo;
```

**script.js reads**
```
mport React from 'react';
import ReactDOM from 'react-dom';
import { useCurrentFrame } from "remotion";
const NeonPath = () => {};

function addIntensity(num) {
  const arr = [];
  while(num) {
    arr.push(<feMergeNode in="blurred" />);
    num--;
  }
  return arr;
}

class Neon extends React.PureComponent {
    componentDidMount() {
                require('./style.css');
    }
    render() {
    const frame = useCurrentFrame();
    const { intensity, blur } = this.props;
    return (
      <div className="neon">
        <svg>  </svg>
);
}
export default Neon;
```

**Package.json reads**
`"scripts": {"make-remotion-video": "remotion render remotion.js NeonArk out.mp4",
                     "start-prod-server": "node client.js",
                     "prod": "npm run start-prod-server"}
....
    "remotion": "2.6.11",
    "@remotion/bundler": "2.6.11",
    "@remotion/cli": "2.6.11",
    "@remotion/eslint-config": "2.6.11",
    "@remotion/renderer": "2.6.11"
`
I even have a index file **index.html** which has
```
<body>
<div id="root"></div>
</body>
```

The error is 

> 📦 (1/3) [====================] Bundled code 1532ms
[Error: Error: Root has not been registered.
    at http://localhost:3000/bundle.js:6409:11
    at http://localhost:3000/bundle.js:6468:3
    at http://localhost:3000/bundle.js:6470:12]
[Error: Error: Root has not been registered.
    at http://localhost:3000/bundle.js:6409:11
    at http://localhost:3000/bundle.js:6468:3
    at http://localhost:3000/bundle.js:6470:12]
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/home/jinxedin/animations/neonark/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:526:34)
    at DOMWorld.waitForFunction (/home/jinxedin/animations/neonark/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:477:26)
    at Frame.waitForFunction (/home/jinxedin/animations/neonark/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:993:32)
    at Page.waitForFunction (/home/jinxedin/animations/neonark/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:2479:33)
    at getCompositions (/home/jinxedin/animations/neonark/node_modules/@remotion/renderer/dist/get-compositions.js:58:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async render (/home/jinxedin/animations/neonark/node_modules/@remotion/cli/dist/render.js:58:19)
    at async cli (/home/jinxedin/animations/neonark/node_modules/@remotion/cli/dist/index.js:41:13)`

What am I missing. Please help!

**Comment by JonnyBurger** [comment]
@rnangia 

Create a new file `index.js`:  

```
import RemotionVideo from './remotion';

registerRoot(RemotionVideo);
```

then change in your package.json:

```diff
- "make-remotion-video": "remotion render remotion.js NeonArk out.mp4"
+ "make-remotion-video": "remotion render index.js NeonArk out.mp4"
```

and it should fix the issue! 🙂

**Comment by rnangia** [comment]
I made those changes. I even deleted the package-lock.json, but I can't shake the error .. What is the "NeonArk placefiller" meant to be?

**Comment by rnangia** [comment]
Had to change to functional components: but now I have this error: Any ideas what causes this? 
```
📦 (1/3) [====================] Bundled code 1368ms
🖼  (2/3) [                    ] Rendering frames (1x) 0/30
The following error occurred when trying to render frame 0:
Error: Minified React error #306; visit https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=%5Bobject%20Object%5D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ck (http://localhost:3000/bundle.js:509:244)
    at bk (http://localhost:3000/bundle.js:490:347)
    at ak (http://localhost:3000/bundle.js:490:278)
    at Tj (http://localhost:3000/bundle.js:490:138)
    at Lj (http://localhost:3000/bundle.js:483:163)
    at http://localhost:3000/bundle.js:363:115
    at exports.unstable_runWithPriority (http://localhost:3000/bundle.js:5826:343)
    at gg (http://localhost:3000/bundle.js:362:325)
    at jg (http://localhost:3000/bundle.js:363:61)
    at V (http://localhost:3000/bundle.js:5824:224)
```

**Comment by JonnyBurger** [comment]
@rnangia The error occurs, when what you return is not React markup, but something else. 

Probably the following code causes the problem:

```
  return (
      <div className="neon">
        <svg>  </svg>
);
```

You forgot to close the tag, change it to this:

```
  return (
      <div className="neon">
        <svg>  </svg>
</div>
);
```
